import { towers, buildableKinds } from '../data/towers';
import { enemyById } from '../data/enemies';
import { difficultyRules } from '../data/difficulty';
import { doctrineFor } from '../data/doctrines';
import type { EnemyDefinition, TargetPriority, TowerKind } from '../data/types';
import type { BarrierInstance, DefenseTeam, EnemyInstance, FacilityInstance, GameSettings, Projectile, Vec2 } from './model';
import { buildWave, previewWave, type SpawnOrder } from '../systems/waves';
import { factionEnemyScale, factionTowerScale } from '../systems/balance';

type TerrainKind='trees'|'brush'|'rocks'|'berm'|'ruin'|'ditch'|'grass';
interface TerrainPatch {x:number;y:number;r:number;kind:TerrainKind;cover:number;concealment:number;blocksLOS:boolean;vehiclePassable:boolean;move:number}
interface Camera {zoom:number;x:number;y:number}

export class Game {
 canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;settings:GameSettings;width=1800;height=1000;credits=1500;wave=0;waveActive=false;waveQueue:SpawnOrder[]=[];spawnTimer=0;prep=true;
 facilities:FacilityInstance[]=[];teams:DefenseTeam[]=[];enemies:EnemyInstance[]=[];projectiles:Projectile[]=[];barriers:BarrierInstance[]=[];terrain:TerrainPatch[]=[];
 selected:{type:'facility'|'team'|'enemy';id:number}|null=null;gameOver=false;victory=false;paused=false;speed=1;activeCooldown=0;activeMax=45;elapsed=0;nextId=1;
 camera:Camera={zoom:1,x:900,y:500};onUpdate:()=>void=()=>{};onGameOver:()=>void=()=>{};onVictory:()=>void=()=>{};onSaved:()=>void=()=>{};
 base={x:680,y:330,w:440,h:340};
 slots:Record<TowerKind,Vec2>={Command:{x:900,y:500},Medical:{x:1000,y:575},Repair:{x:1000,y:425},Infantry:{x:790,y:575},MachineGun:{x:790,y:425},Precision:{x:740,y:380},Indirect:{x:900,y:615},AntiArmor:{x:740,y:620},AirDefense:{x:1060,y:380},CounterUAS:{x:1060,y:620},Recon:{x:900,y:385},Engineering:{x:1010,y:500},Fortification:{x:790,y:500}};
 teamSlots:Partial<Record<TowerKind,Vec2[]>>={
  Infantry:[{x:680,y:410},{x:680,y:590},{x:1120,y:410},{x:1120,y:590}],MachineGun:[{x:680,y:360},{x:680,y:640},{x:1120,y:360},{x:1120,y:640}],Precision:[{x:740,y:330},{x:1060,y:330}],Indirect:[{x:860,y:680},{x:940,y:680}],AntiArmor:[{x:680,y:530},{x:1120,y:530}],AirDefense:[{x:1070,y:330},{x:1070,y:670}],CounterUAS:[{x:1030,y:670},{x:770,y:670}]
 };
 private pointers=new Map<number,{x:number;y:number}>(); private pinchStart=0;private pinchZoom=1;private panStart:{x:number;y:number;cx:number;cy:number}|null=null;
 constructor(canvas:HTMLCanvasElement,settings:GameSettings){this.canvas=canvas;this.ctx=canvas.getContext('2d')!;this.settings=settings;this.createTerrain();this.createBarriers();this.createInitialOutpost();this.bindCanvas();}

 createTerrain(){const pts:[number,number,number,TerrainKind,number,number,boolean,boolean,number][]=[
 [190,180,95,'trees',.25,.65,true,false,.62],[400,120,70,'grass',.04,.28,false,true,.86],[580,180,64,'rocks',.36,.18,true,false,.55],[1230,150,90,'trees',.25,.65,true,false,.62],[1540,230,80,'brush',.08,.55,false,true,.78],
 [170,790,100,'trees',.25,.65,true,false,.62],[430,850,78,'grass',.04,.30,false,true,.86],[590,770,72,'berm',.32,.12,true,false,.55],[1230,820,82,'rocks',.36,.18,true,false,.55],[1540,760,100,'trees',.25,.65,true,false,.62],
 [300,480,74,'ruin',.38,.56,true,false,.58],[1480,500,84,'ruin',.38,.56,true,false,.58],[510,470,55,'brush',.08,.55,false,true,.78],[1300,590,64,'berm',.32,.12,true,false,.55],[840,170,58,'ditch',.24,.32,false,true,.62],[960,850,62,'ditch',.24,.32,false,true,.62]
 ];this.terrain=pts.map(([x,y,r,kind,cover,concealment,blocksLOS,vehiclePassable,move])=>({x,y,r,kind,cover,concealment,blocksLOS,vehiclePassable,move}));}
 createBarriers(){const x=this.base.x,y=this.base.y,w=this.base.w,h=this.base.h;const seg=(a:Vec2,b:Vec2,gate=false)=>this.barriers.push({id:this.nextId++,a,b,hp:gate?650:520,maxHp:gate?650:520,gate,level:0,destroyed:false});
  seg({x,y},{x:x+w*.38,y});seg({x:x+w*.62,y},{x:x+w,y});seg({x:x+w*.38,y},{x:x+w*.62,y},true);seg({x,y:y+h},{x:x+w*.38,y:y+h});seg({x:x+w*.62,y:y+h},{x:x+w,y:y+h});seg({x:x+w*.38,y:y+h},{x:x+w*.62,y:y+h},true);seg({x,y},{x,y:y+h});seg({x:x+w,y},{x:x+w,y:y+h});}
 createInitialOutpost(){for(const k of ['Command','Medical','Repair','Infantry','MachineGun'] as TowerKind[])this.addFacility(k,false);}

 addFacility(kind:TowerKind,pay=true){if(this.facilities.some(f=>f.def.kind===kind))return false;const source=towers[kind];if(pay&&this.credits<source.baseCost)return false;if(pay)this.credits-=source.baseCost;const scale=factionTowerScale(this.settings.playerFaction,this.settings.difficulty);const def={...source,categories:[...source.categories]};const f:FacilityInstance={id:this.nextId++,def,homePos:{...this.slots[kind]},hp:def.maxHp*scale,maxHp:def.maxHp*scale,status:'Idle',upgrades:def.categories.map(name=>({name,level:0})),repairProgress:0,rebuildProgress:0,holdFire:false,targetPriority:'Closest'};this.facilities.push(f);this.ensureTeamsForFacility(f);this.onUpdate();return true;}
 build(kind:TowerKind){if(!buildableKinds.includes(kind))return false;return this.addFacility(kind,true);}
 ensureTeamsForFacility(f:FacilityInstance){const slots=this.teamSlots[f.def.kind];if(!slots)return;const desired=Math.min(slots.length,1+Math.floor(f.upgrades.reduce((s,u)=>s+u.level,0)/4));const have=this.teams.filter(t=>t.facilityId===f.id).length;for(let i=have;i<desired;i++){const p=slots[i];const maxPers=f.def.kind==='Infantry'?6:f.def.kind==='MachineGun'?3:2;this.teams.push({id:this.nextId++,facilityId:f.id,kind:f.def.kind,pos:{...f.homePos},homePos:{...p},hp:f.def.maxHp*.55,maxHp:f.def.maxHp*.55,status:'Deploying',targetId:null,cooldown:0,ammo:f.def.magazine,reloadTimer:0,personnel:maxPers,maxPersonnel:maxPers,casualtyTimers:[],deployTimer:2.4,suppression:0,repairProgress:0,rebuildProgress:0,holdFire:false,targetPriority:'Closest'});}}
 upgrade(facilityId:number,index:number){const f=this.facilities.find(x=>x.id===facilityId);if(!f)return false;const u=f.upgrades[index];if(!u)return false;const base=Math.max(250,f.def.baseCost);const mult=u.level===0?.25:u.level===1?.4:u.level===2?.65:u.level===3?1:1.35**(u.level-3);const cost=Math.round(base*mult);if(this.credits<cost)return false;this.credits-=cost;u.level++;
  const cat=u.name.toLowerCase();if(/fortification|barrier|gate|perimeter|overhead/.test(cat)){for(const b of this.barriers){b.level++;b.maxHp*=1.12;b.hp=Math.min(b.maxHp,b.hp+b.maxHp*.12);}}
  f.maxHp*=1.06;f.hp=Math.min(f.maxHp,f.hp+f.maxHp*.06);this.ensureTeamsForFacility(f);for(const t of this.teams.filter(t=>t.facilityId===f.id)){if(/person|crew|team|operator|observer/.test(cat)){t.maxPersonnel++;t.personnel++;}if(/optic|sensor|observation|detection|communications|intelligence/.test(cat))f.def.range*=1.06;if(/weapon|ammunition|interceptor|defeat|equipment/.test(cat))f.def.damage*=1.10;if(/fire control|sustain|network|target|battle management/.test(cat))f.def.fireRate=Math.max(.08,f.def.fireRate*.94);t.maxHp*=1.04;t.hp=Math.min(t.maxHp,t.hp+t.maxHp*.04);}this.onUpdate();return true;}
 setPriority(id:number,p:TargetPriority){const f=this.facilities.find(x=>x.id===id);if(f){f.targetPriority=p;for(const t of this.teams.filter(t=>t.facilityId===id))t.targetPriority=p;}this.onUpdate();}
 toggleHoldFire(id:number){const f=this.facilities.find(x=>x.id===id);if(f){f.holdFire=!f.holdFire;for(const t of this.teams.filter(t=>t.facilityId===id))t.holdFire=f.holdFire;}this.onUpdate();}

 startWave(){if(this.waveActive||this.gameOver)return;this.wave++;this.waveQueue=buildWave(this.wave,this.settings.difficulty,this.settings.enemyFaction);this.waveActive=true;this.prep=false;this.spawnTimer=.35;this.onUpdate();}
 getThreatPreview(){return previewWave(this.wave+1,this.settings.difficulty,this.settings.enemyFaction);}

 spawnEnemy(def:EnemyDefinition,o:SpawnOrder){const rules=difficultyRules[this.settings.difficulty],fs=factionEnemyScale(this.settings.enemyFaction,this.settings.difficulty),hp=def.hp*rules.enemyHp*fs;const starts=[{x:40,y:170},{x:40,y:830},{x:900,y:40},{x:1760,y:180},{x:1760,y:820}];const s={...starts[o.lane%starts.length]};const doc=doctrineFor(this.settings.enemyFaction);const offset=(o.formationSlot%5-2)*doc.spacing; if(o.lane%5===2)s.x+=offset;else s.y+=offset;const e:EnemyInstance={id:this.nextId++,def,faction:this.settings.enemyFaction,pos:s,hp,maxHp:hp,status:def.role==='recon'||def.role==='recon-uav'?'Recon':'Approaching',attackCooldown:0,troopCount:def.troops,crewCount:def.crew,spawnedFromVehicle:false,groupId:o.groupId,lane:o.lane,cover:0,suppression:0,detection:'Undetected',tacticalState:def.role==='recon'||def.role==='recon-uav'?'Recon':'Approach',objective:{x:900,y:500},waypoint:null,dismounted:false,oneWaySpent:false,orbitAngle:Math.random()*Math.PI*2,formationSlot:o.formationSlot};this.enemies.push(e);}

 update(dt:number){if(this.paused||this.gameOver)return;dt*=this.speed;this.elapsed+=dt;this.activeCooldown=Math.max(0,this.activeCooldown-dt);if(this.waveActive){this.spawnTimer-=dt;if(this.waveQueue.length&&this.spawnTimer<=0){const o=this.waveQueue.shift()!;this.spawnEnemy(enemyById[o.enemyId],o);this.spawnTimer=o.delay;}if(!this.waveQueue.length&&!this.enemies.length){this.waveActive=false;this.prep=true;this.credits+=90+this.wave*15;const goal=4+this.settings.mission;if(this.wave>=goal){this.victory=true;this.gameOver=true;this.onVictory();}}}
  this.updateDetection(dt);this.updateSupport(dt);this.updateEnemies(dt);this.updateTeams(dt);this.updateProjectiles(dt);this.onUpdate();}

 updateDetection(dt:number){const recon=this.facilities.find(f=>f.def.kind==='Recon'&&f.hp>0);const cp=this.facilities.find(f=>f.def.kind==='Command'&&f.hp>0);const reconLvl=recon?recon.upgrades.reduce((s,u)=>s+u.level,0):0,cpLvl=cp?cp.upgrades.reduce((s,u)=>s+u.level,0):0;const baseRange=540+reconLvl*45+cpLvl*12;for(const e of this.enemies){const centerDist=Math.hypot(e.pos.x-900,e.pos.y-500);let vis=baseRange;for(const t of this.terrain){if(Math.hypot(t.x-e.pos.x,t.y-e.pos.y)<t.r)vis*=1-t.concealment*.55;}if(e.def.role==='recon-uav'||e.def.cls==='Aerial')vis+=140;if(centerDist<vis)e.detection='Tracked';else if(centerDist<vis+170)e.detection='Identified';else if(centerDist<vis+300)e.detection='Detected';else if(centerDist<vis+430)e.detection='Suspected';else e.detection='Undetected'; if(recon&&recon.hp>0&&e.detection!=='Undetected'&&reconLvl>0)e.suppression=Math.max(0,e.suppression-dt*.04);}}

 updateSupport(dt:number){const repair=this.facilities.find(f=>f.def.kind==='Repair'&&f.hp>0),eng=this.facilities.find(f=>f.def.kind==='Engineering'&&f.hp>0),med=this.facilities.find(f=>f.def.kind==='Medical'&&f.hp>0);const repairLvl=repair?repair.upgrades.reduce((s,u)=>s+u.level,0):0,engLvl=eng?eng.upgrades.reduce((s,u)=>s+u.level,0):0,medLvl=med?med.upgrades.reduce((s,u)=>s+u.level,0):0;
  if(repair){const cap=1+Math.floor(repairLvl/4),targets=[...this.teams.filter(t=>t.hp>0&&t.hp<t.maxHp),...this.facilities.filter(f=>f.hp>0&&f.hp<f.maxHp)].sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp).slice(0,cap);for(const x of targets){const rate=(5.5+repairLvl*.9)*dt;x.hp=Math.min(x.maxHp,x.hp+rate);x.repairProgress=x.hp/x.maxHp;}}
  if(eng){const destroyed=[...this.teams.filter(t=>t.hp<=0),...this.facilities.filter(f=>f.hp<=0&&f.def.kind!=='Command')].slice(0,1+Math.floor(engLvl/5));for(const x of destroyed){x.rebuildProgress=(x.rebuildProgress||0)+dt*(.018+engLvl*.0025);if(x.rebuildProgress>=1){x.hp=x.maxHp*.45;x.status='Repairing';x.rebuildProgress=0;}}for(const b of this.barriers.filter(b=>b.destroyed||b.hp<b.maxHp).slice(0,1+Math.floor(engLvl/4))){b.hp=Math.min(b.maxHp,b.hp+dt*(8+engLvl));if(b.hp>0){b.destroyed=false;}}}
  for(const t of this.teams){if(!med)continue;t.casualtyTimers=t.casualtyTimers.map(x=>x-dt*(1+medLvl*.08)).filter(x=>{if(x<=0){t.personnel=Math.min(t.maxPersonnel,t.personnel+1);return false;}return true;});}
 }

 updateEnemies(dt:number){const rules=difficultyRules[this.settings.difficulty],doc=doctrineFor(this.settings.enemyFaction);const groups=new Map<number,EnemyInstance[]>();for(const e of this.enemies){const a=groups.get(e.groupId)||[];a.push(e);groups.set(e.groupId,a);}for(const e of [...this.enemies]){if(e.hp<=0){this.killEnemy(e);continue;}e.attackCooldown=Math.max(0,e.attackCooldown-dt);e.suppression=Math.max(0,e.suppression-dt*.10);e.cover=this.terrainAt(e.pos).cover;
   if(e.def.cls==='Aerial'){this.updateAerial(e,dt,rules.enemyDamage);continue;}
   if((e.def.role==='transport'||e.def.role==='ifv')&&!e.dismounted&&e.troopCount>0&&Math.hypot(e.pos.x-900,e.pos.y-500)<doc.dismountDistance){this.dismount(e);}
   const group=groups.get(e.groupId)||[e];const contact=group.some(x=>x.hp<x.maxHp*.98)||group.some(x=>this.nearestTeamDistance(x.pos)<620);if(contact&&e.tacticalState==='Approach')e.tacticalState='Contact';
   if(e.tacticalState==='Recon'){e.status='Recon';this.moveToward(e,this.chooseCoverWaypoint(e,true),dt*.78);if(Math.hypot(e.pos.x-900,e.pos.y-500)<650)e.tacticalState='Contact';continue;}
   if(e.tacticalState==='Contact'){const suppressors=group.filter((_,i)=>i%2===0);if(doc.bounding>.68&&suppressors.includes(e)){e.tacticalState='Suppress';}else e.tacticalState='Maneuver';}
   if(e.tacticalState==='Suppress'){e.status='Suppressing';const target=this.findEnemyTarget(e);if(target&&Math.hypot(target.pos.x-e.pos.x,target.pos.y-e.pos.y)<=e.def.attackRange+90){this.enemyAttack(e,target,dt,rules.enemyDamage,.75);continue;}if(Math.random()<dt*.35)e.tacticalState='Maneuver';}
   if(e.tacticalState==='Maneuver'){e.status=doc.bounding>.7?'Bounding':'Approaching';const wp=this.chooseCoverWaypoint(e,false);this.moveToward(e,wp,dt*(e.suppression>.4?.58:1));if(this.distanceToPerimeter(e.pos)<85)e.tacticalState='Breach';continue;}
   if(e.tacticalState==='Breach'){const breach=this.nearestBarrier(e.pos);if(breach&&!breach.destroyed){e.status='Breaching';this.moveToward(e,this.midpoint(breach.a,breach.b),dt*.7);if(this.dist(e.pos,this.midpoint(breach.a,breach.b))<e.def.attackRange+20){if(e.attackCooldown<=0){breach.hp-=e.def.damage*(e.def.role==='assault'?2.2:1.0);e.attackCooldown=e.def.attackRate;if(breach.hp<=0){breach.destroyed=true;e.tacticalState='Assault';}}}continue;}e.tacticalState='Assault';}
   if(e.tacticalState==='Assault'||e.tacticalState==='Consolidate'){e.status='Assaulting';const target=this.findEnemyTarget(e);if(target){const d=this.dist(e.pos,target.pos);if(d<=e.def.attackRange){this.enemyAttack(e,target,dt,rules.enemyDamage,1);continue;}this.moveToward(e,target.pos,dt*(1+doc.aggression*.08));}else this.moveToward(e,{x:900,y:500},dt);}
  }}

 updateAerial(e:EnemyInstance,dt:number,damageScale:number){if(e.def.role==='recon-uav'){e.status='Recon';e.orbitAngle+=dt*.25;const target={x:900+Math.cos(e.orbitAngle)*520,y:500+Math.sin(e.orbitAngle)*340};this.moveToward(e,target,dt);return;}if(e.def.role==='one-way'){const t=this.findEnemyTarget(e);if(!t){this.moveToward(e,{x:900,y:500},dt);return;}this.moveToward(e,t.pos,dt*1.15);if(this.dist(e.pos,t.pos)<18&&!e.oneWaySpent){t.hp-=e.def.damage*damageScale;e.oneWaySpent=true;e.hp=0;}return;}const t=this.findEnemyTarget(e);if(!t)return;const d=this.dist(e.pos,t.pos);if(d>e.def.attackRange*.78)this.moveToward(e,t.pos,dt*.75);else{e.status='Attacking';this.enemyAttack(e,t,dt,damageScale,1);e.orbitAngle+=dt*.4;e.pos.x+=Math.cos(e.orbitAngle)*8*dt;e.pos.y+=Math.sin(e.orbitAngle)*8*dt;}}

 enemyAttack(e:EnemyInstance,target:{hp:number;pos:Vec2;status:any;personnel?:number;casualtyTimers?:number[]},dt:number,scale:number,mult:number){if(e.attackCooldown>0)return;e.attackCooldown=e.def.attackRate;const hit=e.def.damage*scale*mult*(1-e.suppression*.45);target.hp-=hit;if(target.personnel&&target.casualtyTimers&&Math.random()<Math.min(.32,hit/130)){target.personnel--;target.casualtyTimers.push(22+Math.random()*20);}if(target.hp<=0)target.status='Destroyed';const cp=this.facilities.find(f=>f.def.kind==='Command');if(cp&&cp.hp<=0&&!this.gameOver){this.gameOver=true;this.onGameOver();}}

 findEnemyTarget(e:EnemyInstance):({hp:number;maxHp:number;pos:Vec2;status:any;personnel?:number;casualtyTimers?:number[];kind?:TowerKind})|null{const teams=this.teams.filter(t=>t.hp>0).map(t=>({...t,kind:t.kind}));const facilities=this.facilities.filter(f=>f.hp>0).map(f=>({hp:f.hp,maxHp:f.maxHp,pos:f.homePos,status:f.status,kind:f.def.kind}));let candidates=[...teams,...facilities];if(e.tacticalState!=='Assault')candidates=teams.length?teams:facilities;return candidates.sort((a,b)=>this.dist(e.pos,a.pos)-this.dist(e.pos,b.pos))[0]||null;}

 updateTeams(dt:number){for(const t of this.teams){const f=this.facilities.find(f=>f.id===t.facilityId);if(!f)continue;if(t.hp<=0){t.status='Destroyed';continue;}if(t.deployTimer>0){t.deployTimer-=dt;const d=this.dist(t.pos,t.homePos);if(d>4)this.movePoint(t.pos,t.homePos,90*dt);else t.pos={...t.homePos};t.status='Deploying';continue;}t.suppression=Math.max(0,t.suppression-dt*.12);if(t.personnel<=0||t.holdFire||f.holdFire){t.status=t.personnel<=0?'Disabled':'Idle';continue;}if(t.reloadTimer>0){t.reloadTimer-=dt;t.status='Reloading';if(t.reloadTimer<=0)t.ammo=f.def.magazine;continue;}t.cooldown=Math.max(0,t.cooldown-dt);const target=this.pickTeamTarget(t,f);if(!target){t.status='Idle';t.targetId=null;continue;}t.targetId=target.id;t.status='Tracking';if(t.cooldown<=0){if(t.ammo<=0){t.reloadTimer=f.def.reload;t.status='Reloading';continue;}t.ammo--;t.cooldown=f.def.fireRate*(1+t.suppression*.55);t.status='Firing';const splash=t.kind==='Indirect'?55:0;this.projectiles.push({id:this.nextId++,from:{...t.pos},to:{...target.pos},progress:0,speed:t.kind==='Indirect'?1.6:4.8,damage:f.def.damage,targetId:target.id,splash,kind:t.kind});if(t.kind==='MachineGun'||t.kind==='Indirect')target.suppression=Math.min(1,target.suppression+(t.kind==='MachineGun'?.16:.24));}}
  }

 pickTeamTarget(t:DefenseTeam,f:FacilityInstance){let valid=this.enemies.filter(e=>e.hp>0&&e.detection!=='Undetected'&&f.def.targets.includes(e.def.cls));valid=valid.filter(e=>{const d=this.dist(t.pos,e.pos);if(d>f.def.range||d<(f.def.minRange||0))return false;if(t.kind!=='Indirect'&&this.blockedLOS(t.pos,e.pos))return false;return true;});const p=t.targetPriority;if(p==='Infantry')valid.sort((a,b)=>(a.def.cls==='Infantry'?-1:1)-(b.def.cls==='Infantry'?-1:1));else if(p==='Armor')valid.sort((a,b)=>(a.def.armor==='Heavy'?-3:a.def.armor==='Medium'?-2:0)-(b.def.armor==='Heavy'?-3:b.def.armor==='Medium'?-2:0));else if(p==='Air')valid.sort((a,b)=>(a.def.cls==='Aerial'?-1:1)-(b.def.cls==='Aerial'?-1:1));else if(p==='Drones')valid.sort((a,b)=>(a.def.role?.includes('uav')||a.def.role==='one-way'?-1:1)-(b.def.role?.includes('uav')||b.def.role==='one-way'?-1:1));else if(p==='Strongest')valid.sort((a,b)=>b.maxHp-a.maxHp);else valid.sort((a,b)=>this.dist(t.pos,a.pos)-this.dist(t.pos,b.pos));return valid[0];}

 updateProjectiles(dt:number){for(const p of [...this.projectiles]){p.progress+=dt*p.speed;if(p.progress<1)continue;const target=this.enemies.find(e=>e.id===p.targetId);if(target){let dmg=p.damage*(1-target.cover*.55);if(target.def.armor==='Heavy'&&!['AntiArmor','Indirect'].includes(p.kind))dmg*=.25;else if(target.def.armor==='Medium'&&['Infantry','MachineGun'].includes(p.kind))dmg*=.5;target.hp-=dmg;if(p.splash>0)for(const e of this.enemies)if(e.id!==target.id&&this.dist(e.pos,target.pos)<p.splash)e.hp-=dmg*.42;}this.projectiles.splice(this.projectiles.indexOf(p),1);}}

 killEnemy(e:EnemyInstance){this.credits+=e.def.reward;this.enemies.splice(this.enemies.indexOf(e),1);if(e.def.cls==='Vehicle'&&e.def.manned&&(e.crewCount+e.troopCount)>0&&!e.dismounted){const over=Math.max(0,-e.hp)/e.maxHp,s=Math.max(0,.68-over*.9),surv=Math.round((e.crewCount+e.troopCount)*s);if(surv>0)this.spawnDismountAt(e.pos,surv,e.groupId,e.lane);}if(this.selected?.type==='enemy'&&this.selected.id===e.id)this.selected=null;}
 dismount(e:EnemyInstance){e.dismounted=true;if(e.troopCount>0){this.spawnDismountAt(e.pos,e.troopCount,e.groupId,e.lane);e.troopCount=0;}}
 spawnDismountAt(pos:Vec2,troops:number,groupId:number,lane:number){const d=enemyById.rifle;const hp=d.hp*(.55+Math.min(1,troops/7)*.45);this.enemies.push({id:this.nextId++,def:d,faction:this.settings.enemyFaction,pos:{x:pos.x+12,y:pos.y+12},hp,maxHp:hp,status:'Approaching',attackCooldown:0,troopCount:troops,crewCount:0,spawnedFromVehicle:true,groupId,lane,cover:0,suppression:0,detection:'Detected',tacticalState:'Maneuver',objective:{x:900,y:500},waypoint:null,dismounted:true,oneWaySpent:false,orbitAngle:0,formationSlot:0});}

 chooseCoverWaypoint(e:EnemyInstance,recon:boolean){if(e.waypoint&&this.dist(e.pos,e.waypoint)>24)return e.waypoint;const doc=doctrineFor(this.settings.enemyFaction);const candidates=this.terrain.filter(t=>(e.def.cls!=='Vehicle'||t.vehiclePassable)&&this.dist(e.pos,{x:t.x,y:t.y})<420&&this.dist({x:t.x,y:t.y},{x:900,y:500})<this.dist(e.pos,{x:900,y:500})-40);if(candidates.length&&Math.random()<doc.coverUse){const t=candidates.sort((a,b)=>(b.cover+b.concealment)-(a.cover+a.concealment))[0];e.waypoint={x:t.x+(Math.random()-.5)*t.r*.7,y:t.y+(Math.random()-.5)*t.r*.7};}else{const flank=(Math.random()-.5)*doc.flankChance*360;e.waypoint={x:900+flank,y:500+(e.lane%2?180:-180)};}if(recon)e.waypoint={x:900+(e.lane%2?460:-460),y:500+(e.formationSlot%2?260:-260)};return e.waypoint;}
 moveToward(e:EnemyInstance,target:Vec2,dt:number){const terrain=this.terrainAt(e.pos);const suppressionMult=1-e.suppression*.5;this.movePoint(e.pos,target,e.def.speed*dt*terrain.move*suppressionMult);if(this.dist(e.pos,target)<18)e.waypoint=null;}

 terrainAt(p:Vec2){let cover=0,concealment=0,move=1;for(const t of this.terrain)if(this.dist(p,{x:t.x,y:t.y})<t.r){cover=Math.max(cover,t.cover);concealment=Math.max(concealment,t.concealment);move=Math.min(move,t.move);}return {cover,concealment,move};}
 blockedLOS(a:Vec2,b:Vec2){for(const t of this.terrain.filter(t=>t.blocksLOS)){const abx=b.x-a.x,aby=b.y-a.y,len2=abx*abx+aby*aby;if(!len2)continue;const q=Math.max(0,Math.min(1,((t.x-a.x)*abx+(t.y-a.y)*aby)/len2));const px=a.x+abx*q,py=a.y+aby*q;if(Math.hypot(px-t.x,py-t.y)<t.r*.72)return true;}return false;}
 nearestTeamDistance(p:Vec2){return Math.min(...this.teams.filter(t=>t.hp>0).map(t=>this.dist(p,t.pos)),9999)}
 distanceToPerimeter(p:Vec2){const x=Math.max(this.base.x,Math.min(p.x,this.base.x+this.base.w)),y=Math.max(this.base.y,Math.min(p.y,this.base.y+this.base.h));return this.dist(p,{x,y});}
 nearestBarrier(p:Vec2){return this.barriers.filter(b=>!b.destroyed).sort((a,b)=>this.dist(p,this.midpoint(a.a,a.b))-this.dist(p,this.midpoint(b.a,b.b)))[0]||null;}
 midpoint(a:Vec2,b:Vec2){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}} dist(a:Vec2,b:Vec2){return Math.hypot(a.x-b.x,a.y-b.y)}
 movePoint(p:Vec2,t:Vec2,amount:number){const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy);if(d<=amount||d===0){p.x=t.x;p.y=t.y;return;}p.x+=dx/d*amount;p.y+=dy/d*amount;}

 useActive(){if(this.activeCooldown>0||this.gameOver)return false;this.activeCooldown=this.activeMax;const type=this.settings.playerFaction.activePower.type;if(type==='reinforce'){for(const t of this.teams.filter(t=>['Infantry','MachineGun'].includes(t.kind))){t.personnel=t.maxPersonnel;t.casualtyTimers=[];}}else if(type==='defense'||type==='network'){for(const f of this.facilities)f.hp=Math.min(f.maxHp,f.hp+f.maxHp*.15);for(const t of this.teams)t.suppression=0;}else{for(const e of [...this.enemies].sort((a,b)=>b.maxHp-a.maxHp).slice(0,type==='drone'?6:4))e.hp-=type==='air'?280:type==='fires'?225:195;}this.onUpdate();return true;}

 getSelected(){if(!this.selected)return null;if(this.selected.type==='facility')return this.facilities.find(f=>f.id===this.selected!.id);if(this.selected.type==='team')return this.teams.find(t=>t.id===this.selected!.id);return this.enemies.find(e=>e.id===this.selected!.id);}
 getFacilityForTeam(t:DefenseTeam){return this.facilities.find(f=>f.id===t.facilityId);}

 bindCanvas(){this.canvas.style.touchAction='none';this.canvas.addEventListener('pointerdown',e=>{this.canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===1)this.panStart={x:e.clientX,y:e.clientY,cx:this.camera.x,cy:this.camera.y};if(this.pointers.size===2){const p=[...this.pointers.values()];this.pinchStart=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);this.pinchZoom=this.camera.zoom;}});this.canvas.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===2){const p=[...this.pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(this.pinchStart>0)this.camera.zoom=Math.max(1,Math.min(3.2,this.pinchZoom*d/this.pinchStart));this.clampCamera();this.onUpdate();}else if(this.pointers.size===1&&this.camera.zoom>1&&this.panStart){const r=this.canvas.getBoundingClientRect(),dx=(e.clientX-this.panStart.x)*this.width/r.width/this.camera.zoom,dy=(e.clientY-this.panStart.y)*this.height/r.height/this.camera.zoom;this.camera.x=this.panStart.cx-dx;this.camera.y=this.panStart.cy-dy;this.clampCamera();this.onUpdate();}});const up=(e:PointerEvent)=>{const wasOne=this.pointers.size===1;const start=this.panStart;this.pointers.delete(e.pointerId);if(wasOne&&start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<8)this.selectAt(e.clientX,e.clientY);if(this.pointers.size===0)this.panStart=null;};this.canvas.addEventListener('pointerup',up);this.canvas.addEventListener('pointercancel',up);}
 selectAt(clientX:number,clientY:number){const w=this.screenToWorld(clientX,clientY);let bestE:EnemyInstance|null=null,bd=28/this.camera.zoom;for(const e of this.enemies){const d=this.dist(e.pos,w);if(d<bd){bestE=e;bd=d;}}if(bestE){this.selected={type:'enemy',id:bestE.id};this.onUpdate();return;}let bestT:DefenseTeam|null=null;bd=34/this.camera.zoom;for(const t of this.teams){const d=this.dist(t.pos,w);if(d<bd){bestT=t;bd=d;}}if(bestT){this.selected={type:'team',id:bestT.id};this.onUpdate();return;}let bestF:FacilityInstance|null=null;bd=38/this.camera.zoom;for(const f of this.facilities){const d=this.dist(f.homePos,w);if(d<bd){bestF=f;bd=d;}}this.selected=bestF?{type:'facility',id:bestF.id}:null;this.onUpdate();}
 resetView(){this.camera={zoom:1,x:900,y:500};this.onUpdate();}
 clampCamera(){const halfW=this.width/(2*this.camera.zoom),halfH=this.height/(2*this.camera.zoom);this.camera.x=Math.max(halfW,Math.min(this.width-halfW,this.camera.x));this.camera.y=Math.max(halfH,Math.min(this.height-halfH,this.camera.y));}
 screenToWorld(cx:number,cy:number){const r=this.canvas.getBoundingClientRect(),sx=(cx-r.left)/r.width,sy=(cy-r.top)/r.height;const vw=this.width/this.camera.zoom,vh=this.height/this.camera.zoom;return{x:this.camera.x-vw/2+sx*vw,y:this.camera.y-vh/2+sy*vh};}
 worldToScreen(p:Vec2){const vw=this.width/this.camera.zoom,vh=this.height/this.camera.zoom;return{x:(p.x-(this.camera.x-vw/2))/vw,y:(p.y-(this.camera.y-vh/2))/vh};}

 draw(){const c=this.ctx;c.clearRect(0,0,this.width,this.height);c.save();const z=this.camera.zoom;c.translate(this.width/2,this.height/2);c.scale(z,z);c.translate(-this.camera.x,-this.camera.y);c.fillStyle='#7b8067';c.fillRect(0,0,this.width,this.height);this.drawTerrain(c);this.drawRoads(c);this.drawBase(c);this.drawBarriers(c);this.drawFacilities(c);this.drawTeams(c);this.drawEnemies(c);this.drawProjectiles(c);this.drawSelection(c);c.restore();}
 drawTerrain(c:CanvasRenderingContext2D){for(const t of this.terrain){c.save();c.translate(t.x,t.y);if(t.kind==='trees'){c.fillStyle='#465b3a';for(let i=0;i<7;i++){const a=i/7*Math.PI*2;c.beginPath();c.arc(Math.cos(a)*t.r*.45,Math.sin(a)*t.r*.35,t.r*.28,0,Math.PI*2);c.fill();}}else if(t.kind==='brush'||t.kind==='grass'){c.fillStyle=t.kind==='brush'?'#64734b':'#8b8f61';c.beginPath();c.ellipse(0,0,t.r,t.r*.62,0,0,Math.PI*2);c.fill();}else if(t.kind==='rocks'||t.kind==='berm'){c.fillStyle=t.kind==='rocks'?'#67675e':'#776d50';c.beginPath();c.ellipse(0,0,t.r,t.r*.45,0,0,Math.PI*2);c.fill();}else if(t.kind==='ruin'){c.fillStyle='#6f655d';c.fillRect(-t.r*.7,-t.r*.45,t.r*1.4,t.r*.9);c.fillStyle='#3f3a37';c.fillRect(-t.r*.5,-t.r*.22,t.r*.35,t.r*.28);c.fillRect(t.r*.12,-t.r*.1,t.r*.38,t.r*.32);}else{c.strokeStyle='#5d6650';c.lineWidth=18;c.beginPath();c.moveTo(-t.r,0);c.lineTo(t.r,0);c.stroke();}c.restore();}}
 drawRoads(c:CanvasRenderingContext2D){c.strokeStyle='#857d69';c.lineWidth=26;c.lineCap='round';for(const [a,b] of [[{x:0,y:500},{x:680,y:500}],[{x:1120,y:500},{x:1800,y:500}],[{x:900,y:0},{x:900,y:330}],[{x:900,y:670},{x:900,y:1000}]] as [Vec2,Vec2][]){c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}}
 drawBase(c:CanvasRenderingContext2D){c.fillStyle='#77745f';c.fillRect(this.base.x,this.base.y,this.base.w,this.base.h);c.strokeStyle='#454941';c.lineWidth=4;c.strokeRect(this.base.x,this.base.y,this.base.w,this.base.h);}
 drawBarriers(c:CanvasRenderingContext2D){for(const b of this.barriers){if(b.destroyed)continue;c.strokeStyle=b.gate?'#4e4d45':'#565b50';c.lineWidth=5+b.level*1.3;c.beginPath();c.moveTo(b.a.x,b.a.y);c.lineTo(b.b.x,b.b.y);c.stroke();if(b.hp<b.maxHp*.45){c.strokeStyle='#8d5d45';c.lineWidth=2;c.stroke();}}}
 drawFacilities(c:CanvasRenderingContext2D){for(const f of this.facilities){const p=f.homePos;c.save();c.translate(p.x,p.y);const k=f.def.kind;c.fillStyle=f.hp<=0?'#3a302d':'#394650';if(k==='Medical')c.fillStyle='#e8e5dc';if(k==='Repair')c.fillStyle='#4e5860';if(k==='Command')c.fillStyle='#344152';if(k==='Recon')c.fillStyle='#4b5148';if(k==='Engineering')c.fillStyle='#625747';if(k==='Fortification')c.fillStyle='#5a5b4e';c.fillRect(-24,-18,48,36);c.strokeStyle='#171d22';c.strokeRect(-24,-18,48,36);c.fillStyle=k==='Medical'?'#9d2d2d':'#eef2f4';c.font='bold 13px system-ui';c.textAlign='center';const labels:Record<TowerKind,string>={Command:'CP',Medical:'MED',Repair:'REP',Infantry:'INF HQ',MachineGun:'MG HQ',Precision:'PREC',Indirect:'MTR',AntiArmor:'AT',AirDefense:'AD',CounterUAS:'C-UAS',Recon:'RECON',Engineering:'ENG',Fortification:'FORT'};c.fillText(labels[k],0,5);if(k==='Medical'){c.fillStyle='#9d2d2d';c.fillRect(-4,-12,8,24);c.fillRect(-12,-4,24,8);}c.restore();}}
 drawTeams(c:CanvasRenderingContext2D){for(const t of this.teams){c.save();c.translate(t.pos.x,t.pos.y);c.fillStyle=t.hp<=0?'#3a302d':'#2f3e35';c.beginPath();c.arc(0,0,14,0,Math.PI*2);c.fill();c.fillStyle='#d7d0b3';for(let i=0;i<t.personnel;i++){const a=i/Math.max(1,t.maxPersonnel)*Math.PI*2;c.beginPath();c.arc(Math.cos(a)*19,Math.sin(a)*19,3.2,0,Math.PI*2);c.fill();}c.strokeStyle='#171d22';c.lineWidth=3;if(t.kind==='MachineGun'){c.beginPath();c.moveTo(-10,0);c.lineTo(16,0);c.stroke();c.fillRect(8,-4,8,8);}else if(t.kind==='Indirect'){c.beginPath();c.moveTo(-3,7);c.lineTo(8,-13);c.stroke();}else if(t.kind==='AntiArmor'){c.fillRect(-10,-3,24,6);}else if(t.kind==='AirDefense'){c.beginPath();c.moveTo(-8,8);c.lineTo(8,-10);c.stroke();c.moveTo(2,8);c.lineTo(16,-6);c.stroke();}else if(t.kind==='CounterUAS'){c.beginPath();c.arc(0,0,9,Math.PI,Math.PI*2);c.stroke();c.moveTo(0,0);c.lineTo(0,-15);c.stroke();}else{c.beginPath();c.moveTo(-8,5);c.lineTo(12,-6);c.stroke();}c.restore();}}
 drawEnemies(c:CanvasRenderingContext2D){for(const e of this.enemies){if(e.detection==='Undetected')continue;c.save();c.translate(e.pos.x,e.pos.y);c.globalAlpha=e.detection==='Suspected'?.35:e.detection==='Detected'?.6:1;c.fillStyle=e.def.color;if(e.def.cls==='Infantry'){c.beginPath();c.arc(0,0,e.def.radius,0,Math.PI*2);c.fill();for(let i=0;i<Math.min(5,e.troopCount);i++){c.beginPath();c.arc((i-2)*6,15+(i%2)*4,2.5,0,Math.PI*2);c.fill();}}else if(e.def.cls==='Vehicle'){c.fillRect(-e.def.radius,-e.def.radius*.65,e.def.radius*2,e.def.radius*1.3);c.fillStyle='#333a33';c.fillRect(-e.def.radius*.65,-e.def.radius*.85,e.def.radius*1.3,e.def.radius*.42);if(e.def.role==='tank'){c.strokeStyle='#222';c.lineWidth=4;c.beginPath();c.moveTo(0,-3);c.lineTo(e.def.radius*1.5,-12);c.stroke();}}else{c.beginPath();c.moveTo(-e.def.radius*1.5,0);c.lineTo(0,-e.def.radius*.45);c.lineTo(e.def.radius*1.5,0);c.lineTo(0,e.def.radius*.45);c.closePath();c.fill();}if(e.suppression>.35){c.fillStyle='#d9c55c';c.fillRect(-14,-24,28,3);}c.restore();}}
 drawProjectiles(c:CanvasRenderingContext2D){for(const p of this.projectiles){const x=p.from.x+(p.to.x-p.from.x)*p.progress,y=p.from.y+(p.to.y-p.from.y)*p.progress;c.fillStyle=p.kind==='Indirect'?'#252525':'#f0d88a';c.beginPath();c.arc(x,y,p.kind==='Indirect'?4:2,0,Math.PI*2);c.fill();}}
 drawSelection(c:CanvasRenderingContext2D){if(!this.selected)return;if(this.selected.type==='facility'){const f=this.facilities.find(f=>f.id===this.selected!.id);if(!f)return;c.strokeStyle='#e6d27c';c.lineWidth=4;c.strokeRect(f.homePos.x-31,f.homePos.y-25,62,50);for(const t of this.teams.filter(t=>t.facilityId===f.id))this.drawRange(c,t,f);}else if(this.selected.type==='team'){const t=this.teams.find(t=>t.id===this.selected!.id);if(!t)return;const f=this.getFacilityForTeam(t);if(f)this.drawRange(c,t,f);c.strokeStyle='#e6d27c';c.lineWidth=3;c.beginPath();c.arc(t.pos.x,t.pos.y,24,0,Math.PI*2);c.stroke();}else{const e=this.enemies.find(e=>e.id===this.selected!.id);if(e){c.strokeStyle='#f0d06a';c.beginPath();c.arc(e.pos.x,e.pos.y,e.def.radius+8,0,Math.PI*2);c.stroke();}}}
 drawRange(c:CanvasRenderingContext2D,t:DefenseTeam,f:FacilityInstance){if(!f.def.range)return;c.strokeStyle='rgba(240,220,120,.75)';c.lineWidth=2;c.beginPath();c.arc(t.pos.x,t.pos.y,f.def.range,0,Math.PI*2);c.stroke();if(f.def.minRange){c.strokeStyle='rgba(220,120,100,.7)';c.beginPath();c.arc(t.pos.x,t.pos.y,f.def.minRange,0,Math.PI*2);c.stroke();}}
}
