import { buildings,buildableBuildings,upgrades } from '../data/buildings';
import { difficultyRules } from '../data/difficulty';
import { doctrineFor } from '../data/doctrines';
import { equipmentById } from '../data/equipment';
import { units } from '../data/units';
import type { BuildingKind,ContactClass,GameSettings,UnitOrder,UnitRole } from '../data/types';
import type { BarrierInstance,BuildingInstance,ContactEvent,Effect,Projectile,SoldierInstance,TerrainPatch,UnitInstance,UpgradeView,Vec2 } from './model';
import { buildEnemyWave,previewEnemyWave,unitExists,type SpawnOrder } from '../systems/waves';
import { audio } from '../systems/audio';

interface Camera{zoom:number;x:number;y:number}
interface Selection{type:'building'|'unit';id:number}

export class Game{
 canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;settings:GameSettings;width=1920;height=1080;credits:number;phase=0;phaseActive=false;phaseQueue:SpawnOrder[]=[];spawnTimer=0;gameOver=false;victory=false;paused=false;speed=1;elapsed=0;score=0;activeCooldown=0;activeMax=45;
 buildings:BuildingInstance[]=[];units:UnitInstance[]=[];barriers:BarrierInstance[]=[];terrain:TerrainPatch[]=[];projectiles:Projectile[]=[];effects:Effect[]=[];events:ContactEvent[]=[];selection:Selection|null=null;camera:Camera={zoom:1,x:960,y:540};nextId=1;objective={x:960,y:540,r:95};enemyObjective={x:1640,y:540,r:110};
 onUpdate:()=>void=()=>{};onVictory:()=>void=()=>{};onGameOver:()=>void=()=>{};onEvent:(t:string,p:'Routine'|'Warning'|'Critical')=>void=()=>{};
 pendingOrder:UnitOrder|null=null;private pointers=new Map<number,{x:number;y:number}>();private pinchStart=0;private pinchZoom=1;private panStart:{x:number;y:number;cx:number;cy:number}|null=null;private dragMoved=false;
 constructor(canvas:HTMLCanvasElement,settings:GameSettings){this.canvas=canvas;this.ctx=canvas.getContext('2d')!;this.settings=settings;this.credits=settings.mission.startingCredits;audio.configure(settings.masterVolume,settings.effectsVolume,settings.voiceVolume,settings.voiceFrequency);this.createMap();this.createMissionStart();this.bindCanvas();this.resetView();}

 createMap(){this.terrain=[];let id=1;const add=(kind:TerrainPatch['kind'],x:number,y:number,rx:number,ry:number,cover:number,conceal:number,los:boolean,veh:boolean,move:number,elev:number)=>this.terrain.push({id:id++,kind,x,y,rx,ry,cover,concealment:conceal,blocksLOS:los,vehiclePassable:veh,move,elevation:elev});
  const theme=this.settings.mission.mapTheme;const tree=theme==='Desert'?'Rock':theme==='Urban'?'Ruin':'Trees';
  add('Road',120,510,1680,64,0,0,false,true,1.12,0);add(tree as any,250,230,130,95,.28,.58,true,false,.64,1);add('Brush',520,160,120,70,.08,.52,false,true,.82,0);add('Berm',740,270,115,52,.34,.12,true,false,.6,1);add('Ditch',930,810,180,45,.22,.28,false,true,.68,-1);add('Rock',1260,220,100,72,.38,.15,true,false,.58,1);add(tree as any,1500,820,150,105,.28,.58,true,false,.64,1);add('Ruin',350,780,120,100,.4,.48,true,false,.55,1);add('Grass',1100,690,190,100,.04,.25,false,true,.9,0);add('Mud',1420,440,120,80,.08,.08,false,true,.58,-.3);add('Berm',1580,320,100,48,.34,.12,true,false,.6,1);
  if(theme==='Coastal')add('Water',1040,140,480,65,0,0,false,false,.1,-1);if(theme==='Snow')add('Mud',650,880,360,95,.04,.04,false,true,.7,0);if(theme==='Urban'){add('Ruin',850,185,100,80,.42,.55,true,false,.52,1);add('Ruin',1190,850,130,90,.42,.55,true,false,.52,1)}
 }
 createMissionStart(){const type=this.settings.mission.type;if(type==='BaseDefense'){this.createBuilding('Command',false,{x:960,y:540});this.objective={x:960,y:540,r:100};this.createBaseBarriers();this.addEvent('Command Post established. Build combat facilities before the main attack.','Routine');}
  else if(type==='FieldDefense'||type==='Delay'){this.objective={x:870,y:540,r:130};this.predeployFieldForce();this.addEvent('No permanent base. Hold the objective with your deployed force.','Warning');}
  else {this.objective={x:300,y:540,r:100};this.enemyObjective={x:1640,y:540,r:115};this.predeployAssaultForce();this.spawnEnemyDefenders();this.addEvent('Enemy strongpoint located. Seize the objective.','Warning');}
 }
 createBaseBarriers(){const cx=this.objective.x,cy=this.objective.y,w=430,h=330,x=cx-w/2,y=cy-h/2;const seg=(a:Vec2,b:Vec2,gate=false)=>this.barriers.push({id:this.nextId++,a,b,hp:gate?600:460,maxHp:gate?600:460,gate,cover:.35,destroyed:false});seg({x,y},{x:x+w*.38,y});seg({x:x+w*.62,y},{x:x+w,y});seg({x:x+w*.38,y},{x:x+w*.62,y},true);seg({x,y:y+h},{x:x+w*.38,y:y+h});seg({x:x+w*.62,y:y+h},{x:x+w,y:y+h});seg({x:x+w*.38,y:y+h},{x:x+w*.62,y:y+h},true);seg({x,y},{x,y:y+h});seg({x:x+w,y},{x:x+w,y:y+h});}
 createBuilding(kind:BuildingKind,pay=true,pos?:Vec2){if(this.buildings.some(b=>b.kind===kind))return false;const def=buildings[kind];if(pay&&this.credits<def.baseCost)return false;if(pay)this.credits-=def.baseCost;const positions:Record<BuildingKind,Vec2>={Command:{x:960,y:540},Infantry:{x:840,y:610},AirDefense:{x:1080,y:430},MotorPool:{x:1080,y:610},Aviation:{x:840,y:430}};this.buildings.push({id:this.nextId++,kind,pos:{...(pos||positions[kind])},hp:kind==='Command'?1800:kind==='MotorPool'?1000:850,maxHp:kind==='Command'?1800:kind==='MotorPool'?1000:850,upgrades:{},status:'Operational'});this.onUpdate();return true}
 build(kind:BuildingKind){if(this.settings.mission.type!=='BaseDefense'||!buildableBuildings.includes(kind))return false;return this.createBuilding(kind,true)}

 getUpgradeViews(b:BuildingInstance):UpgradeView[]{const owned=this.buildings.map(x=>x.kind);return upgrades.filter(u=>u.building===b.kind).map(def=>{const level=b.upgrades[def.id]||0;let locked='';for(const r of def.requires){const found=this.buildings.some(x=>(x.upgrades[r]||0)>0);if(!found)locked=`Requires ${upgrades.find(x=>x.id===r)?.name||r}`;}if(level>=def.maxLevel)locked='MAX';return {def,level,lockedReason:locked,cost:Math.round(def.cost*(1+level*.55)),effectNow:def.effect}})}
 buyUpgrade(buildingId:number,upgradeId:string){const b=this.buildings.find(x=>x.id===buildingId),def=upgrades.find(x=>x.id===upgradeId);if(!b||!def||def.building!==b.kind)return false;const view=this.getUpgradeViews(b).find(x=>x.def.id===upgradeId);if(!view||view.lockedReason||this.credits<view.cost)return false;this.credits-=view.cost;b.upgrades[upgradeId]=(b.upgrades[upgradeId]||0)+1;if(def.kind==='fortification')this.applyFortificationUpgrade(def.id);this.addEvent(`${def.name} purchased: ${def.effect}`,'Routine');audio.ui();this.onUpdate();return true}
 applyFortificationUpgrade(id:string){if(id==='cp-fort-1'){for(const p of [{x:720,y:430},{x:720,y:650},{x:1200,y:430},{x:1200,y:650}])this.terrain.push({id:this.nextId++,kind:'Berm',x:p.x,y:p.y,rx:70,ry:34,cover:.42,concealment:.08,blocksLOS:false,vehiclePassable:false,move:.65,elevation:.4});}
  if(id==='cp-fort-2')for(const t of this.terrain.filter(t=>t.kind==='Berm'))t.cover=Math.min(.65,t.cover+.18);if(id==='cp-fort-3')for(const b of this.barriers){b.maxHp*=1.5;b.hp=b.maxHp;b.cover=.5;}}

 availableUnitIds(){const kinds=this.buildings.map(b=>b.kind);const ids:string[]=[];if(kinds.includes('Infantry'))ids.push('rifle','mg','mortar','precision','at','engineer');if(kinds.includes('AirDefense'))ids.push('sam','cuas');if(kinds.includes('MotorPool')){if(this.isUnlocked('apc-unlock'))ids.push('apc');if(this.isUnlocked('ifv-unlock'))ids.push('ifv');if(this.isUnlocked('tank-unlock'))ids.push('tank');ids.push('recon-vehicle','recovery')}if(kinds.includes('Aviation')){if(this.isUnlocked('recon-uav-unlock'))ids.push('recon-drone');if(this.isUnlocked('armed-uav-unlock'))ids.push('armed-drone');if(this.isUnlocked('helo-unlock'))ids.push('helicopter');ids.push('interceptor-drone')}return ids}
 isUnlocked(id:string){return [this.settings.loadout.personnel,this.settings.loadout.primary,this.settings.loadout.supportWeapon,this.settings.loadout.optic,this.settings.loadout.armor,...this.settings.loadout.specialists,this.settings.loadout.vehicle,this.settings.loadout.aviation,...this.settings.loadout.support].includes(id)||['regular','service-rifle','iron','standard-armor','none-support','no-vehicle','no-aviation'].includes(id)}
 capacityFor(unitId:string){const d=units[unitId];if(!d)return 0;if(d.domain==='Vehicle'){const b=this.buildings.find(x=>x.kind==='MotorPool');return b?1+(b.upgrades['mp-bay']||0):0}if(d.domain==='Aerial'){const b=this.buildings.find(x=>x.kind==='Aviation');return b?1+(b.upgrades['av-sortie']||0):0}if(d.role==='Rifle'){const b=this.buildings.find(x=>x.kind==='Infantry');return b?1+(b.upgrades['inf-squad']||0):0}if(d.role==='SAM'||d.role==='CounterUAS'){const b=this.buildings.find(x=>x.kind==='AirDefense');return b?1+(b.upgrades['ad-team']||0):0}return this.buildings.some(x=>x.kind==='Infantry')?2:0}
 deployUnit(unitId:string,pay=true,pos?:Vec2){const def=units[unitId];if(!def)return false;const same=this.units.filter(u=>u.side==='Friendly'&&u.def.id===unitId&&!u.destroyed).length;if(same>=this.capacityFor(unitId)&&this.settings.mission.type==='BaseDefense')return false;if(pay&&this.credits<def.cost)return false;if(pay)this.credits-=def.cost;const spawn=pos||this.nextFriendlyPosition(def.domain);const u=this.makeUnit(def,'Friendly',spawn,0,same);this.applyLoadout(u);this.applyOrganizationWeapons(u);this.units.push(u);this.addEvent(`${def.name} deployed.`,'Routine');audio.speak(`${def.name} ready.`,'en-US');this.onUpdate();return true}
 nextFriendlyPosition(domain:string){const n=this.units.filter(u=>u.side==='Friendly').length;if(domain==='Aerial')return {x:this.objective.x+(n%2?130:-130),y:this.objective.y-210};const ring=210+Math.floor(n/6)*35,a=(n%6)/6*Math.PI*2;return {x:this.objective.x+Math.cos(a)*ring,y:this.objective.y+Math.sin(a)*ring}}
 makeUnit(def:any,side:'Friendly'|'Enemy',pos:Vec2,groupId:number,slot:number):UnitInstance{const rules=difficultyRules[this.settings.difficulty],enemy=side==='Enemy';const hp=def.hp*(enemy?rules.enemyHp:1);const count=def.domain==='Infantry'?def.personnel:0;const soldiers:SoldierInstance[]=Array.from({length:count},(_,i)=>({id:this.nextId++,offset:this.soldierOffset(i,count),hp:100,maxHp:100,state:'Ready',medic:false,engineer:def.role==='Engineer',casualtyTimer:0,phase:Math.random()*10}));return {id:this.nextId++,side,def:{...def},role:def.role,pos:{...pos},destination:{...pos},hp,maxHp:hp,order:'Hold',status:'Ready',soldiers,weapons:def.weaponsPerTeam,ammo:def.magazine,reloadTimer:0,cooldown:Math.random()*.5,targetId:null,suppression:0,cover:0,detection:side==='Friendly'?'Tracked':'Undetected',groupId,formationSlot:slot,objective:side==='Enemy'?{...this.objective}:{...this.enemyObjective},aiState:side==='Enemy'?'Approach':'Hold',disabled:false,destroyed:false,passengers:0,endurance:def.endurance||999,turnaround:0,selected:false,veterancy:0,medicBusy:false,setupTimer:0}}
 soldierOffset(i:number,count:number){const row=Math.floor(i/3),col=i%3,spread=12;return {x:(col-1)*spread+(row%2?6:0),y:(row-(Math.ceil(count/3)-1)/2)*spread}}
 applyLoadout(u:UnitInstance){if(u.side!=='Friendly'||u.def.domain!=='Infantry')return;const items=[equipmentById[this.settings.loadout.personnel],equipmentById[this.settings.loadout.primary],equipmentById[this.settings.loadout.supportWeapon],equipmentById[this.settings.loadout.optic],equipmentById[this.settings.loadout.armor],...this.settings.loadout.specialists.map(x=>equipmentById[x])].filter(Boolean);for(const it of items){const s=it.stats||{};u.def.damage*=1+(s.damage||0);u.def.speed*=1+(s.speed||0);u.maxHp*=1+(s.hp||0);u.hp=u.maxHp;if(s.medic){const target=u.soldiers.find(x=>!x.medic);if(target)target.medic=true}if(s.crew){}if(it.id==='sof')u.veterancy=3;else if(it.id==='elite')u.veterancy=Math.max(u.veterancy,2);else if(it.id==='veteran')u.veterancy=Math.max(u.veterancy,1)}if(this.settings.loadout.specialists.includes('engineer')){const x=u.soldiers.find(s=>!s.medic);if(x)x.engineer=true}}
 applyOrganizationWeapons(u:UnitInstance){if(u.side!=='Friendly'||u.def.domain!=='Infantry')return;const inf=this.buildings.find(x=>x.kind==='Infantry');if(!inf)return;let extra=0;if(u.role==='MachineGun')extra=inf.upgrades['inf-mg-gun']||0;if(u.role==='Mortar')extra=inf.upgrades['inf-mortar-tube']||0;const personExpansion=(inf.upgrades['inf-personnel']||0)*2;const available=u.soldiers.length+personExpansion;const maxWeapons=Math.max(1,Math.floor(available/Math.max(1,u.def.crewPerWeapon)));u.weapons=Math.min(u.def.weaponsPerTeam+extra,maxWeapons)}
 predeployFieldForce(){this.deployUnit('rifle',false,{x:760,y:450});this.deployUnit('rifle',false,{x:760,y:620});this.deployUnit('mg',false,{x:850,y:400});if(this.settings.loadout.vehicle!=='no-vehicle'){const id=this.settings.loadout.vehicle.replace('-unlock','');if(units[id])this.units.push(this.makeUnit(units[id],'Friendly',{x:800,y:700},0,0))}this.predeployAviation({x:690,y:300})}
 predeployAssaultForce(){this.deployUnit('rifle',false,{x:250,y:450});this.deployUnit('rifle',false,{x:250,y:600});this.units.push(this.makeUnit(units.mg,'Friendly',{x:320,y:690},0,0));if(this.settings.loadout.vehicle!=='no-vehicle'){const id=this.settings.loadout.vehicle.replace('-unlock','');if(units[id])this.units.push(this.makeUnit(units[id],'Friendly',{x:220,y:760},0,0))}this.predeployAviation({x:200,y:260})}
 predeployAviation(pos:Vec2){const map:Record<string,string>={'recon-uav-unlock':'recon-drone','armed-uav-unlock':'armed-drone','helo-unlock':'helicopter'};const id=map[this.settings.loadout.aviation];if(id&&units[id])this.units.push(this.makeUnit(units[id],'Friendly',pos,0,0))}
 spawnEnemyDefenders(){const defs=[['rifle',1500,430],['mg',1550,610],['at',1660,420],['rifle',1700,650]] as any[];for(let i=0;i<defs.length;i++){const [id,x,y]=defs[i];const u=this.makeUnit(units[id],'Enemy',{x,y},1,i);u.order='Defend';u.aiState='Hold';u.objective={...this.enemyObjective};this.units.push(u)}this.barriers.push({id:this.nextId++,a:{x:1510,y:360},b:{x:1510,y:720},hp:720,maxHp:720,gate:false,cover:.5,destroyed:false});}

 setOrderMode(order:UnitOrder){this.pendingOrder=order;this.addEvent(`${order}: tap a destination.`, 'Routine');this.onUpdate()}
 issueOrder(order:UnitOrder,destination?:Vec2){const selected=this.units.filter(u=>u.side==='Friendly'&&u.selected&&!u.destroyed);for(const u of selected){u.order=order;if(destination){u.destination={...destination};u.status=order;u.setupTimer=u.role==='Mortar'||u.role==='MachineGun'?1.8:0}if(order==='Fallback')u.destination={...this.objective};}if(selected.length){audio.ui();audio.speak(order==='Assault'?'Assaulting objective.':order==='Move'?'Moving.':`${order}.`,'en-US');this.addEvent(`${selected.length} unit${selected.length>1?'s':''}: ${order}.`,'Routine')}}
 selectAt(world:Vec2,add=false){let best:UnitInstance|BuildingInstance|null=null,type:'unit'|'building'='unit',dist=40;for(const u of this.units.filter(x=>!x.destroyed)){const d=Math.hypot(u.pos.x-world.x,u.pos.y-world.y);if(d<dist){dist=d;best=u;type='unit'}}for(const b of this.buildings){const d=Math.hypot(b.pos.x-world.x,b.pos.y-world.y);if(d<42){dist=d;best=b;type='building'}}if(!add)for(const u of this.units)u.selected=false;if(best){this.selection={type,id:(best as any).id};if(type==='unit'&&(best as UnitInstance).side==='Friendly')(best as UnitInstance).selected=true}else this.selection=null;this.onUpdate()}
 getSelected(){if(!this.selection)return null;return this.selection.type==='unit'?this.units.find(x=>x.id===this.selection!.id)||null:this.buildings.find(x=>x.id===this.selection!.id)||null}
 selectedFriendly(){return this.units.filter(u=>u.selected&&u.side==='Friendly'&&!u.destroyed)}

 startPhase(){if(this.phaseActive||this.gameOver)return false;this.phase++;this.phaseQueue=buildEnemyWave(this.phase,this.settings.mission.enemyEscalation,this.settings.difficulty,doctrineFor(this.settings.enemyFaction));this.phaseActive=true;this.spawnTimer=.3;this.addEvent(this.phase===1?'Enemy probing attack detected.':this.phase>=this.settings.mission.waves?'Enemy main attack underway.':'Enemy reinforcement package approaching.','Warning');audio.speak('Enemy movement detected.','en-US',true);return true}
 threatPreview(){return previewEnemyWave(this.phase+1,this.settings.mission.enemyEscalation)}
 spawnEnemy(o:SpawnOrder){const def=unitExists(o.unitId);let pos:Vec2;const type=this.settings.mission.type;if(type==='Assault'||type==='Seize')pos={x:1780,y:180+(o.lane%3)*320};else{const starts=[{x:40,y:170},{x:40,y:900},{x:960,y:40},{x:1880,y:180},{x:1880,y:900}];pos={...starts[o.lane%starts.length]};const doc=doctrineFor(this.settings.enemyFaction),off=(o.formationSlot%5-2)*doc.spacing;if(o.lane%5===2)pos.x+=off;else pos.y+=off}const u=this.makeUnit(def,'Enemy',pos,o.groupId,o.formationSlot);u.objective={...this.objective};this.units.push(u)}

 update(dt:number){if(this.paused||this.gameOver)return;dt*=this.speed;this.elapsed+=dt;this.activeCooldown=Math.max(0,this.activeCooldown-dt);if(this.phaseActive){this.spawnTimer-=dt;if(this.phaseQueue.length&&this.spawnTimer<=0){const o=this.phaseQueue.shift()!;this.spawnEnemy(o);this.spawnTimer=o.delay}if(!this.phaseQueue.length&&!this.units.some(u=>u.side==='Enemy'&&!u.destroyed&&u.aiState!=='Hold')){this.phaseActive=false;this.credits+=120+this.phase*25;if(this.phase>=this.settings.mission.waves&&(this.settings.mission.type==='BaseDefense'||this.settings.mission.type==='FieldDefense'||this.settings.mission.type==='Delay'))this.finishVictory()}}
  this.updateDetection(dt);this.updateMedics(dt);this.updateUnits(dt);this.updateProjectiles(dt);this.updateEffects(dt);this.checkObjectives();for(const e of this.events)e.age+=dt;this.events=this.events.filter(e=>e.age<8);this.onUpdate()}
 updateDetection(_dt:number){const cp=this.buildings.find(b=>b.kind==='Command'&&b.hp>0),reconLevel=cp?.upgrades['cp-recon-1']||0;const base=470*(1+reconLevel*.18)+(this.settings.loadout.support.includes('uav-scan')?120:0);for(const e of this.units.filter(u=>u.side==='Enemy'&&!u.destroyed)){let range=base;const nearbyRecon=this.units.filter(u=>u.side==='Friendly'&&(u.role==='ReconVehicle'||u.role==='ReconDrone')&&!u.destroyed).some(u=>Math.hypot(u.pos.x-e.pos.x,u.pos.y-e.pos.y)<700);if(nearbyRecon)range+=240;const conceal=this.terrainAt(e.pos).concealment;range*=1-conceal*.45;const d=Math.hypot(e.pos.x-this.objective.x,e.pos.y-this.objective.y);e.detection=d<range?'Tracked':d<range+160?'Identified':d<range+300?'Detected':d<range+420?'Suspected':'Undetected'}}
 updateMedics(dt:number){const wounded=this.units.flatMap(u=>u.side==='Friendly'&&!u.destroyed?u.soldiers.filter(s=>s.state==='Wounded').map(s=>({u,s})):[]);const medics=this.units.flatMap(u=>u.side==='Friendly'&&!u.destroyed?u.soldiers.filter(s=>s.medic&&s.state!=='Wounded').map(s=>({u,s})):[]);for(const m of medics){if(!wounded.length)break;let best=wounded[0],bd=Infinity;for(const w of wounded){const d=Math.hypot(m.u.pos.x-w.u.pos.x,m.u.pos.y-w.u.pos.y);if(d<bd){bd=d;best=w}}if(bd<420){m.s.state='Treating';best.s.casualtyTimer-=dt*(1.1+m.u.veterancy*.08);if(best.s.casualtyTimer<=0){best.s.state='Ready';best.s.hp=55;best.u.hp=Math.min(best.u.maxHp,best.u.hp+best.u.maxHp/Math.max(1,best.u.soldiers.length)*.5);this.addEffect('Smoke',best.u.pos,18,.45);const i=wounded.indexOf(best);if(i>=0)wounded.splice(i,1)}}}}
 updateUnits(dt:number){const enemies=this.units.filter(u=>u.side==='Enemy'&&!u.destroyed),friendlies=this.units.filter(u=>u.side==='Friendly'&&!u.destroyed);for(const u of [...friendlies,...enemies]){if(u.destroyed)continue;if(u.hp<=0){this.destroyUnit(u);continue}u.cooldown=Math.max(0,u.cooldown-dt);u.reloadTimer=Math.max(0,u.reloadTimer-dt);u.suppression=Math.max(0,u.suppression-dt*.08);u.cover=this.terrainAt(u.pos).cover;u.endurance-=u.def.domain==='Aerial'?dt:0;if(u.def.domain==='Aerial'&&u.endurance<=0){u.aiState='Return';u.destination=u.side==='Friendly'?{x:100,y:80}:{x:1820,y:80}}
   if(u.side==='Enemy')this.updateEnemyAI(u,dt);else this.updateFriendlyAI(u,dt);this.updateCombat(u,dt)}}
 updateFriendlyAI(u:UnitInstance,dt:number){if(u.disabled)return;const moving=['Move','Assault','Breach','Fallback','Escort'].includes(u.order);if(moving&&Math.hypot(u.destination.x-u.pos.x,u.destination.y-u.pos.y)>12)this.moveUnit(u,u.destination,dt,1);else if(moving){u.order=u.order==='Assault'?'Assault':'Hold';u.status=u.order;u.setupTimer=Math.max(u.setupTimer,.4)}if(u.setupTimer>0)u.setupTimer=Math.max(0,u.setupTimer-dt)}
 updateEnemyAI(u:UnitInstance,dt:number){if(u.disabled)return;const doc=doctrineFor(this.settings.enemyFaction);const target=this.findTarget(u);const targetDist=target?Math.hypot(target.pos.x-u.pos.x,target.pos.y-u.pos.y):9999;const range=this.effectiveRange(u);if(target&&targetDist<range*1.15){u.aiState=u.suppression>.55?'Maneuver':doc.suppression>.82?'Suppress':'Contact';if(u.suppression>.6&&doc.coverUse>.75){const cover=this.bestNearbyCover(u.pos,150);if(cover)this.moveUnit(u,cover,dt,.85)}else if(doc.bounding>.82&&u.def.domain==='Infantry'&&Math.random()<dt*.45){const lateral=(Math.random()-.5)*180;this.moveUnit(u,{x:u.pos.x+(u.objective.x-u.pos.x)*.12,y:u.pos.y+lateral},dt,.9)}}else if(u.aiState!=='Hold'&&u.aiState!=='Return'){u.aiState='Approach';let dest={...u.objective};if(doc.flankChance>.7&&u.groupId%2===0)dest.y+=u.groupId%4===0?-180:180;if(doc.coverUse>.82){const cover=this.bestCoverToward(u.pos,dest,240);if(cover)dest=cover}this.moveUnit(u,dest,dt,1)}if(u.aiState==='Return'&&Math.hypot(u.pos.x-u.destination.x,u.pos.y-u.destination.y)<25)u.destroyed=true}
 moveUnit(u:UnitInstance,dest:Vec2,dt:number,mult:number){let dx=dest.x-u.pos.x,dy=dest.y-u.pos.y,d=Math.hypot(dx,dy);if(d<1)return;const t=this.terrainAt(u.pos);let speed=u.def.speed*t.move*mult*(1-u.suppression*.35);if(u.def.domain==='Vehicle'&&!t.vehiclePassable)speed*=.18;if(u.def.domain==='Aerial')speed=u.def.speed;dx/=d;dy/=d;u.pos.x+=dx*speed*dt;u.pos.y+=dy*speed*dt;u.status='Moving';for(const s of u.soldiers)s.state=s.state==='Wounded'?s.state:'Moving'}
 updateCombat(u:UnitInstance,dt:number){if(u.disabled||u.setupTimer>0||u.def.damage<=0||u.weapons<=0)return;const target=this.findTarget(u);if(!target)return;const d=Math.hypot(target.pos.x-u.pos.x,target.pos.y-u.pos.y),range=this.effectiveRange(u);if(d>range||(u.def.minRange&&d<u.def.minRange)||!this.hasLOS(u.pos,target.pos,u.def.role==='Mortar'))return;if(u.reloadTimer>0)return;if(u.ammo<=0){u.reloadTimer=u.def.reload;u.ammo=u.def.magazine;u.status='Reloading';for(const s of u.soldiers)if(s.state!=='Wounded')s.state='Reloading';return}if(u.cooldown>0)return;u.cooldown=u.def.fireRate*(1+u.suppression*.45);u.ammo=Math.max(0,u.ammo-1);u.status='Firing';for(const s of u.soldiers)if(s.state!=='Wounded'&&s.state!=='Treating')s.state='Firing';const kind=u.role==='Mortar'?'Shell':u.role==='AntiArmor'||u.role==='SAM'?'Missile':u.role==='Tank'||u.role==='IFV'?'Shell':'Tracer';const splash=kind==='Shell'?u.role==='Mortar'?65:38:kind==='Missile'?28:0;const damage=u.def.damage*Math.max(1,u.weapons)*(1-u.suppression*.28);this.projectiles.push({id:this.nextId++,kind,from:{...u.pos},to:{...target.pos},progress:0,speed:kind==='Tracer'?1100:kind==='Missile'?560:420,damage,targetId:target.id,splash,side:u.side});this.addEffect('Muzzle',u.pos,8,.08);audio.shot(kind==='Tracer'?(u.role==='MachineGun'?'mg':'rifle'):kind==='Missile'?'missile':u.role==='Mortar'?'mortar':'cannon')}
 effectiveRange(u:UnitInstance){if(u.side==='Enemy')return u.def.range;const cp=this.buildings.find(b=>b.kind==='Command'),lvl=cp?.upgrades['cp-recon-1']||0;const optic=equipmentById[this.settings.loadout.optic]?.tier||0;const factor=1+Math.min(.28,lvl*.1+optic*.035);return u.def.range*factor}
 findTarget(u:UnitInstance){const targets=this.units.filter(x=>x.side!==u.side&&!x.destroyed&&this.canTarget(u,x)&&((u.side==='Enemy')||x.detection!=='Undetected'));let best:UnitInstance|null=null,bd=Infinity;for(const t of targets){const d=Math.hypot(t.pos.x-u.pos.x,t.pos.y-u.pos.y);if(d<bd){bd=d;best=t}}return best}
 canTarget(a:UnitInstance,b:UnitInstance){const cls:ContactClass=b.def.domain==='Aerial'?'Aerial':b.def.domain==='Vehicle'?'Vehicle':'Infantry';return a.def.targets.includes(cls)}
 updateProjectiles(dt:number){for(const p of [...this.projectiles]){const d=Math.hypot(p.to.x-p.from.x,p.to.y-p.from.y);p.progress+=dt*p.speed/Math.max(1,d);if(p.progress>=1){const target=this.units.find(u=>u.id===p.targetId&&!u.destroyed);const impact=target?target.pos:p.to;this.resolveImpact(p,target||null);this.projectiles.splice(this.projectiles.indexOf(p),1);this.addEffect(p.kind==='Tracer'?'Impact':'Explosion',impact,p.kind==='Shell'?42:p.kind==='Missile'?34:10,p.kind==='Tracer'?.18:.65);if(p.kind!=='Tracer')audio.explosion(p.kind==='Shell'?1.2:1)}}}
 resolveImpact(p:Projectile,target:UnitInstance|null){if(target)this.damageUnit(target,p.damage);if(p.splash>0)for(const u of this.units.filter(x=>x.side!==p.side&&!x.destroyed&&(!target||x.id!==target.id))){const d=Math.hypot(u.pos.x-p.to.x,u.pos.y-p.to.y);if(d<p.splash)this.damageUnit(u,p.damage*.45*(1-d/p.splash))}if(p.splash>25)this.terrain.push({id:this.nextId++,kind:'Crater',x:p.to.x,y:p.to.y,rx:18+p.splash*.2,ry:12+p.splash*.14,cover:.12,concealment:.04,blocksLOS:false,vehiclePassable:true,move:.82,elevation:-.2})}
 damageUnit(u:UnitInstance,amount:number){const cover=1-u.cover*.55;u.hp-=amount*cover;u.suppression=Math.min(1,u.suppression+Math.min(.38,amount/u.maxHp*.9));if(u.def.domain==='Infantry'&&u.soldiers.length&&Math.random()<Math.min(.7,amount/u.maxHp*2.5)){const candidates=u.soldiers.filter(s=>s.state!=='Wounded');const s=candidates[Math.floor(Math.random()*candidates.length)];if(s){s.state='Wounded';s.hp=20;s.casualtyTimer=12+Math.random()*12;u.status='Casualty';audio.speak('Medic!','en-US',true)}}if(u.def.domain==='Vehicle'&&u.hp<u.maxHp*.25&&!u.disabled&&Math.random()<.15){u.disabled=true;u.status='Disabled';this.addEvent(`${u.def.name} disabled.`,'Critical')}}
 destroyUnit(u:UnitInstance){u.destroyed=true;u.hp=0;u.status='Destroyed';this.addEffect('Explosion',u.pos,u.def.domain==='Vehicle'?55:28,.8);if(u.def.domain==='Vehicle')this.addEffect('Fire',u.pos,36,6);if(u.side==='Enemy'){this.score+=Math.round(u.maxHp*.15);this.credits+=Math.max(6,Math.round(u.def.cost*.035))}else this.addEvent(`${u.def.name} lost.`,'Critical')}
 updateEffects(dt:number){for(const e of this.effects)e.age+=dt;this.effects=this.effects.filter(e=>e.age<e.life)}
 checkObjectives(){const type=this.settings.mission.type;if(type==='BaseDefense'){const cp=this.buildings.find(b=>b.kind==='Command');if(cp){for(const e of this.units.filter(u=>u.side==='Enemy'&&!u.destroyed)){const d=Math.hypot(e.pos.x-cp.pos.x,e.pos.y-cp.pos.y);if(d<70){cp.hp-=.22*difficultyRules[this.settings.difficulty].enemyDamage;cp.status=cp.hp<cp.maxHp*.5?'Damaged':'Operational';if(cp.hp<=0){cp.status='Destroyed';this.finishLoss()}}}}}
  if(type==='FieldDefense'||type==='Delay'){const enemies=this.units.filter(u=>u.side==='Enemy'&&!u.destroyed&&Math.hypot(u.pos.x-this.objective.x,u.pos.y-this.objective.y)<this.objective.r);const friend=this.units.some(u=>u.side==='Friendly'&&!u.destroyed&&Math.hypot(u.pos.x-this.objective.x,u.pos.y-this.objective.y)<this.objective.r);if(enemies.length>=3&&!friend)this.finishLoss()}
  if(type==='Assault'||type==='Seize'){const friend=this.units.filter(u=>u.side==='Friendly'&&!u.destroyed&&Math.hypot(u.pos.x-this.enemyObjective.x,u.pos.y-this.enemyObjective.y)<this.enemyObjective.r);const defenders=this.units.some(u=>u.side==='Enemy'&&!u.destroyed&&Math.hypot(u.pos.x-this.enemyObjective.x,u.pos.y-this.enemyObjective.y)<220);if(friend.length>=1&&!defenders)this.finishVictory();if(!this.units.some(u=>u.side==='Friendly'&&!u.destroyed))this.finishLoss()}}
 finishVictory(){if(this.gameOver)return;this.victory=true;this.gameOver=true;this.addEvent('MISSION COMPLETE','Routine');audio.speak('Objective secure. Mission complete.','en-US',true);this.onVictory()}
 finishLoss(){if(this.gameOver)return;this.gameOver=true;this.victory=false;this.addEvent('MISSION FAILED','Critical');audio.speak('Mission failed.','en-US',true);this.onGameOver()}
 useActive(){if(this.activeCooldown>0||this.gameOver)return false;this.activeCooldown=this.activeMax*(1-(this.buildings.find(b=>b.kind==='Command')?.upgrades['cp-command-1']||0)*.1);const targets=this.units.filter(u=>u.side==='Enemy'&&!u.destroyed).sort((a,b)=>b.hp-a.hp).slice(0,4);if(this.settings.playerFaction.activePower.type==='reinforce'){this.deployUnit('rifle',false);return true}const precision=this.settings.loadout.support.includes('precision-support')?1.25:1;if(this.settings.loadout.support.includes('smoke-support')){for(let i=0;i<8;i++)this.addEffect('Smoke',{x:this.objective.x+(Math.random()-.5)*180,y:this.objective.y+(Math.random()-.5)*180},42,3.5);}for(const t of targets){this.damageUnit(t,(this.settings.playerFaction.activePower.type==='defense'||this.settings.playerFaction.activePower.type==='network'?35:145)*precision);this.addEffect('Explosion',t.pos,34,.6)}this.addEvent(`${this.settings.playerFaction.activePower.name} activated.`,'Warning');audio.explosion(1.1);return true}

 terrainAt(p:Vec2){let best={cover:0,concealment:0,move:1,vehiclePassable:true,elevation:0};for(const t of this.terrain){const dx=(p.x-t.x)/t.rx,dy=(p.y-t.y)/t.ry;if(dx*dx+dy*dy<=1){best={cover:Math.max(best.cover,t.cover),concealment:Math.max(best.concealment,t.concealment),move:Math.min(best.move,t.move),vehiclePassable:best.vehiclePassable&&t.vehiclePassable,elevation:Math.max(best.elevation,t.elevation)}}}return best}
 hasLOS(a:Vec2,b:Vec2,indirect=false){if(indirect)return true;for(const t of this.terrain.filter(x=>x.blocksLOS)){for(let i=1;i<12;i++){const q={x:a.x+(b.x-a.x)*i/12,y:a.y+(b.y-a.y)*i/12};const dx=(q.x-t.x)/t.rx,dy=(q.y-t.y)/t.ry;if(dx*dx+dy*dy<.72)return false}}return true}
 bestNearbyCover(p:Vec2,r:number){let best:Vec2|null=null,score=0;for(const t of this.terrain){const d=Math.hypot(t.x-p.x,t.y-p.y);if(d<r&&t.cover>score&&t.kind!=='Water'){best={x:t.x,y:t.y};score=t.cover}}return best}
 bestCoverToward(p:Vec2,dest:Vec2,r:number){let best:Vec2|null=null,score=-1;for(const t of this.terrain){const d=Math.hypot(t.x-p.x,t.y-p.y);if(d>r||t.kind==='Water')continue;const toward=Math.hypot(t.x-dest.x,t.y-dest.y),s=t.cover*.9-toward*.00025;if(s>score){score=s;best={x:t.x,y:t.y}}}return best}
 addEffect(kind:Effect['kind'],pos:Vec2,size:number,life:number){this.effects.push({id:this.nextId++,kind,pos:{...pos},age:0,life,size,rotation:Math.random()*Math.PI*2})}
 addEvent(text:string,priority:ContactEvent['priority']){const e={id:this.nextId++,text,priority,age:0};this.events.unshift(e);this.events=this.events.slice(0,7);this.onEvent(text,priority)}

 bindCanvas(){this.canvas.style.touchAction='none';this.canvas.addEventListener('pointerdown',e=>{audio.ensure();this.canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});this.dragMoved=false;if(this.pointers.size===2){const p=[...this.pointers.values()];this.pinchStart=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);this.pinchZoom=this.camera.zoom;this.panStart=null}else if(this.camera.zoom>1.01)this.panStart={x:e.clientX,y:e.clientY,cx:this.camera.x,cy:this.camera.y}});this.canvas.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;const prev=this.pointers.get(e.pointerId)!;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(Math.hypot(prev.x-e.clientX,prev.y-e.clientY)>3)this.dragMoved=true;if(this.pointers.size===2){const p=[...this.pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);this.camera.zoom=Math.max(1,Math.min(3,this.pinchZoom*d/Math.max(1,this.pinchStart)));this.clampCamera()}else if(this.panStart&&this.camera.zoom>1){const rect=this.canvas.getBoundingClientRect(),scale=this.width/(rect.width*this.camera.zoom);this.camera.x=this.panStart.cx-(e.clientX-this.panStart.x)*scale;this.camera.y=this.panStart.cy-(e.clientY-this.panStart.y)*scale;this.clampCamera()}});const end=(e:PointerEvent)=>{const was=this.pointers.size;this.pointers.delete(e.pointerId);if(was===1&&!this.dragMoved){const world=this.screenToWorld(e.clientX,e.clientY);if(this.pendingOrder&&this.selectedFriendly().length){this.issueOrder(this.pendingOrder,world);this.pendingOrder=null;this.onUpdate()}else this.selectAt(world,e.shiftKey)}this.panStart=null};this.canvas.addEventListener('pointerup',end);this.canvas.addEventListener('pointercancel',end)}
 resetView(){this.camera.zoom=1;this.camera.x=this.width/2;this.camera.y=this.height/2;this.clampCamera()}
 clampCamera(){const halfW=this.width/(2*this.camera.zoom),halfH=this.height/(2*this.camera.zoom);this.camera.x=Math.max(halfW,Math.min(this.width-halfW,this.camera.x));this.camera.y=Math.max(halfH,Math.min(this.height-halfH,this.camera.y))}
 screenToWorld(clientX:number,clientY:number){const r=this.canvas.getBoundingClientRect(),sx=(clientX-r.left)/r.width,sy=(clientY-r.top)/r.height,vw=this.width/this.camera.zoom,vh=this.height/this.camera.zoom;return {x:this.camera.x-vw/2+sx*vw,y:this.camera.y-vh/2+sy*vh}}
 worldToScreen(p:Vec2){const vw=this.width/this.camera.zoom,vh=this.height/this.camera.zoom;return {x:(p.x-(this.camera.x-vw/2))/vw,y:(p.y-(this.camera.y-vh/2))/vh}}

 draw(){const c=this.ctx;c.clearRect(0,0,this.canvas.width,this.canvas.height);const sx=this.canvas.width/(this.width/this.camera.zoom),sy=this.canvas.height/(this.height/this.camera.zoom);c.save();c.scale(sx,sy);c.translate(-(this.camera.x-this.width/(2*this.camera.zoom)),-(this.camera.y-this.height/(2*this.camera.zoom)));this.drawBackground(c);this.drawTerrain(c);this.drawObjectives(c);this.drawBarriers(c);this.drawBuildings(c);this.drawUnits(c);this.drawProjectiles(c);this.drawEffects(c);c.restore()}
 drawBackground(c:CanvasRenderingContext2D){const g=c.createLinearGradient(0,0,0,this.height);g.addColorStop(0,'#6f795c');g.addColorStop(1,'#4d5945');c.fillStyle=g;c.fillRect(0,0,this.width,this.height);c.fillStyle='rgba(255,255,255,.035)';for(let i=0;i<140;i++){const x=(i*137)%this.width,y=(i*241)%this.height;c.fillRect(x,y,2,2)}}
 drawTerrain(c:CanvasRenderingContext2D){for(const t of this.terrain){c.save();c.translate(t.x,t.y);if(t.kind==='Road'){c.fillStyle='#6d6b60';c.fillRect(-t.rx,-t.ry,t.rx*2,t.ry*2);c.strokeStyle='rgba(220,210,170,.28)';c.setLineDash([28,22]);c.beginPath();c.moveTo(-t.rx,0);c.lineTo(t.rx,0);c.stroke();c.setLineDash([])}else if(t.kind==='Trees'){for(let i=0;i<8;i++){const a=i/8*Math.PI*2,r=t.rx*.45+(i%2)*18;c.fillStyle=i%2?'#253f2b':'#315339';c.beginPath();c.arc(Math.cos(a)*r,Math.sin(a)*t.ry*.5,24+(i%3)*5,0,Math.PI*2);c.fill()}}else if(t.kind==='Brush'||t.kind==='Grass'){c.fillStyle=t.kind==='Brush'?'#46613a':'#71815b';c.beginPath();c.ellipse(0,0,t.rx,t.ry,0,0,Math.PI*2);c.fill();c.strokeStyle='rgba(230,235,190,.18)';for(let i=-4;i<=4;i++){c.beginPath();c.moveTo(i*t.rx/5,t.ry*.5);c.lineTo(i*t.rx/5+8,-t.ry*.5);c.stroke()}}else if(t.kind==='Rock'||t.kind==='Berm'||t.kind==='Ruin'){c.fillStyle=t.kind==='Berm'?'#756c50':t.kind==='Ruin'?'#686960':'#777970';c.beginPath();c.roundRect(-t.rx,-t.ry,t.rx*2,t.ry*2,18);c.fill();if(t.kind==='Ruin'){c.strokeStyle='#333';c.lineWidth=6;c.beginPath();c.moveTo(-t.rx*.6,-t.ry*.8);c.lineTo(t.rx*.4,t.ry*.5);c.moveTo(t.rx*.5,-t.ry*.7);c.lineTo(-t.rx*.3,t.ry*.8);c.stroke()}}else if(t.kind==='Ditch'||t.kind==='Mud'||t.kind==='Crater'){c.fillStyle=t.kind==='Mud'?'#594d3e':'#454c3d';c.beginPath();c.ellipse(0,0,t.rx,t.ry,0,0,Math.PI*2);c.fill()}else if(t.kind==='Water'){c.fillStyle='#456b78';c.beginPath();c.ellipse(0,0,t.rx,t.ry,0,0,Math.PI*2);c.fill()}c.restore()}}
 drawObjectives(c:CanvasRenderingContext2D){const type=this.settings.mission.type;const draw=(p:Vec2,r:number,label:string,color:string)=>{c.save();c.strokeStyle=color;c.lineWidth=4;c.setLineDash([12,10]);c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.stroke();c.setLineDash([]);c.fillStyle='rgba(0,0,0,.46)';c.fillRect(p.x-76,p.y-r-34,152,26);c.fillStyle='#fff';c.font='bold 16px system-ui';c.textAlign='center';c.fillText(label,p.x,p.y-r-15);c.restore()};draw(this.objective,this.objective.r,type==='BaseDefense'?'OUTPOST':'FRIENDLY OBJECTIVE','#86d58b');if(type==='Assault'||type==='Seize')draw(this.enemyObjective,this.enemyObjective.r,'ENEMY OBJECTIVE','#e88979')}
 drawBarriers(c:CanvasRenderingContext2D){for(const b of this.barriers){c.strokeStyle=b.destroyed?'rgba(80,70,60,.35)':b.gate?'#6a5b42':'#9a8b68';c.lineWidth=b.gate?14:9;c.beginPath();c.moveTo(b.a.x,b.a.y);c.lineTo(b.b.x,b.b.y);c.stroke();if(!b.destroyed){const mx=(b.a.x+b.b.x)/2,my=(b.a.y+b.b.y)/2;c.fillStyle='rgba(0,0,0,.55)';c.fillRect(mx-24,my-18,48,6);c.fillStyle='#78b868';c.fillRect(mx-24,my-18,48*(b.hp/b.maxHp),6)}}}
 drawBuildings(c:CanvasRenderingContext2D){for(const b of this.buildings){c.save();c.translate(b.pos.x,b.pos.y);c.fillStyle=b.kind==='Command'?'#253646':'#35403c';c.strokeStyle=this.selection?.type==='building'&&this.selection.id===b.id?'#ffd96b':'#aab7ad';c.lineWidth=4;c.beginPath();c.roundRect(-42,-32,84,64,8);c.fill();c.stroke();c.fillStyle='#1b2223';c.fillRect(-28,-23,56,11);if(b.kind==='Command'){c.strokeStyle='#c9d7df';c.lineWidth=3;c.beginPath();c.moveTo(0,-32);c.lineTo(0,-62);c.stroke();c.beginPath();c.arc(0,-66,8,0,Math.PI*2);c.stroke()}if(b.kind==='MotorPool'){c.fillStyle='#202629';c.fillRect(-33,7,66,18)}if(b.kind==='Aviation'){c.strokeStyle='#d5d8d2';c.beginPath();c.moveTo(-22,0);c.lineTo(22,0);c.moveTo(0,-16);c.lineTo(0,16);c.stroke()}c.fillStyle='#f1f4ed';c.font='bold 12px system-ui';c.textAlign='center';c.fillText(buildings[b.kind].name.replace(' Facility',''),0,54);c.fillStyle='#202020';c.fillRect(-35,38,70,6);c.fillStyle=b.hp>b.maxHp*.45?'#69b96d':'#d36c5d';c.fillRect(-35,38,70*Math.max(0,b.hp/b.maxHp),6);c.restore()}}
 drawUnits(c:CanvasRenderingContext2D){for(const u of this.units.filter(x=>!x.destroyed)){if(u.side==='Enemy'&&u.detection==='Undetected')continue;c.save();c.translate(u.pos.x,u.pos.y);if(u.selected){c.strokeStyle='#ffd85f';c.lineWidth=3;c.beginPath();c.arc(0,0,u.def.radius+12,0,Math.PI*2);c.stroke();c.strokeStyle='rgba(255,216,95,.35)';c.lineWidth=2;c.beginPath();c.arc(0,0,this.effectiveRange(u),0,Math.PI*2);c.stroke()}if(u.def.domain==='Infantry')this.drawInfantryUnit(c,u);else if(u.def.domain==='Vehicle')this.drawVehicle(c,u);else this.drawAircraft(c,u);c.restore();this.drawUnitStatus(c,u)} }
 drawInfantryUnit(c:CanvasRenderingContext2D,u:UnitInstance){const friendly=u.side==='Friendly',base=friendly?'#4f7b55':'#8d5f51';for(let i=0;i<u.soldiers.length;i++){const s=u.soldiers[i],jitter=s.state==='Moving'?Math.sin(this.elapsed*8+s.phase)*2:0;c.save();c.translate(s.offset.x+jitter,s.offset.y);c.fillStyle=s.state==='Wounded'?'#70443d':base;c.beginPath();c.arc(0,-5,4.2,0,Math.PI*2);c.fill();c.strokeStyle='#1b1e1c';c.lineWidth=2;c.beginPath();c.moveTo(0,-1);c.lineTo(0,8);c.moveTo(-4,3);c.lineTo(5,4);c.moveTo(0,8);c.lineTo(-4,14);c.moveTo(0,8);c.lineTo(5,14);c.stroke();c.strokeStyle=s.medic?'#e9e9e9':'#262b28';c.lineWidth=2;c.beginPath();c.moveTo(3,2);c.lineTo(11,0);c.stroke();if(s.medic){c.fillStyle='#f1f1f1';c.fillRect(-3,1,6,6);c.fillStyle='#b84949';c.fillRect(-1,2,2,4);c.fillRect(-2,3,4,2)}c.restore()}if(u.role==='Mortar'){c.strokeStyle='#242622';c.lineWidth=5;c.beginPath();c.moveTo(8,8);c.lineTo(15,-8);c.stroke()}if(u.role==='MachineGun'){c.strokeStyle='#202320';c.lineWidth=4;c.beginPath();c.moveTo(6,7);c.lineTo(20,3);c.stroke()} }
 drawVehicle(c:CanvasRenderingContext2D,u:UnitInstance){const friendly=u.side==='Friendly';c.fillStyle=friendly?'#4f6750':'#75574d';c.strokeStyle='#20251f';c.lineWidth=3;const w=u.role==='Tank'?50:46,h=u.role==='APC'?25:29;c.beginPath();c.roundRect(-w/2,-h/2,w,h,7);c.fill();c.stroke();c.fillStyle='#343d34';if(u.role==='Tank'||u.role==='IFV'){c.beginPath();c.arc(2,-2,u.role==='Tank'?11:9,0,Math.PI*2);c.fill();c.strokeStyle='#20251f';c.lineWidth=5;c.beginPath();c.moveTo(7,-3);c.lineTo(u.role==='Tank'?35:28,-8);c.stroke()}else if(u.role==='RecoveryVehicle'){c.strokeStyle='#d0b36a';c.lineWidth=4;c.beginPath();c.moveTo(-10,-5);c.lineTo(20,-22);c.lineTo(26,-8);c.stroke()}else{c.strokeStyle='#20251f';c.lineWidth=3;c.beginPath();c.moveTo(0,-5);c.lineTo(24,-7);c.stroke()}c.fillStyle='#151918';for(const x of [-18,-6,6,18]){c.beginPath();c.arc(x,h/2+3,4,0,Math.PI*2);c.arc(x,-h/2-3,4,0,Math.PI*2);c.fill()} }
 drawAircraft(c:CanvasRenderingContext2D,u:UnitInstance){const friendly=u.side==='Friendly';c.fillStyle=friendly?'#7e9496':'#987e76';c.strokeStyle='#263032';c.lineWidth=2;if(u.role==='Helicopter'){c.beginPath();c.ellipse(0,0,23,10,0,0,Math.PI*2);c.fill();c.stroke();c.strokeStyle='#1f2425';c.beginPath();c.moveTo(-36,0);c.lineTo(36,0);c.moveTo(0,-31);c.lineTo(0,31);c.stroke()}else{c.beginPath();c.moveTo(26,0);c.lineTo(-8,-10);c.lineTo(-24,-4);c.lineTo(-12,0);c.lineTo(-24,4);c.lineTo(-8,10);c.closePath();c.fill();c.stroke()} }
 drawUnitStatus(c:CanvasRenderingContext2D,u:UnitInstance){const p=u.pos;c.fillStyle='rgba(12,15,14,.68)';c.fillRect(p.x-30,p.y+u.def.radius+14,60,7);c.fillStyle=u.hp/u.maxHp>.5?'#6fbd72':u.hp/u.maxHp>.25?'#d6a458':'#d7665a';c.fillRect(p.x-30,p.y+u.def.radius+14,60*Math.max(0,u.hp/u.maxHp),7);if(u.suppression>.25){c.fillStyle='#e4be61';c.font='11px system-ui';c.textAlign='center';c.fillText('SUPPRESSED',p.x,p.y+u.def.radius+36)}if(u.disabled){c.fillStyle='#f2a05d';c.fillText('DISABLED',p.x,p.y+u.def.radius+48)}}
 drawProjectiles(c:CanvasRenderingContext2D){for(const p of this.projectiles){const x=p.from.x+(p.to.x-p.from.x)*p.progress,y=p.from.y+(p.to.y-p.from.y)*p.progress;c.strokeStyle=p.kind==='Tracer'?(p.side==='Friendly'?'#ffe082':'#ff9d79'):'#e8e6db';c.lineWidth=p.kind==='Tracer'?2:4;c.beginPath();c.moveTo(x-(p.to.x-p.from.x)*.02,y-(p.to.y-p.from.y)*.02);c.lineTo(x,y);c.stroke();if(p.kind==='Missile'){c.fillStyle='rgba(230,230,220,.45)';c.beginPath();c.arc(x-6,y+4,7,0,Math.PI*2);c.fill()}}}
 drawEffects(c:CanvasRenderingContext2D){const quality=this.settings.graphics;for(const e of this.effects){const t=e.age/e.life,a=Math.max(0,1-t);c.save();c.translate(e.pos.x,e.pos.y);c.rotate(e.rotation);if(e.kind==='Explosion'){const r=e.size*(.45+t*.9);const g=c.createRadialGradient(0,0,0,0,0,r);g.addColorStop(0,`rgba(255,245,190,${a})`);g.addColorStop(.35,`rgba(255,145,45,${a*.9})`);g.addColorStop(1,'rgba(70,55,45,0)');c.fillStyle=g;c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.fill();if(quality!=='Battery'){c.fillStyle=`rgba(65,62,58,${a*.45})`;for(let i=0;i<5;i++){c.beginPath();c.arc(Math.cos(i*2.1)*r*.5,Math.sin(i*1.7)*r*.4,r*.25,0,Math.PI*2);c.fill()}}}else if(e.kind==='Muzzle'){c.fillStyle=`rgba(255,225,120,${a})`;c.beginPath();c.moveTo(0,0);c.lineTo(e.size*2,-e.size*.6);c.lineTo(e.size*1.3,0);c.lineTo(e.size*2,e.size*.6);c.closePath();c.fill()}else if(e.kind==='Impact'||e.kind==='Spark'){c.fillStyle=`rgba(255,220,150,${a})`;for(let i=0;i<4;i++){c.fillRect(Math.cos(i*1.7)*e.size*t,Math.sin(i*1.9)*e.size*t,3,3)}}else if(e.kind==='Smoke'||e.kind==='Fire'){c.fillStyle=e.kind==='Fire'?`rgba(210,90,35,${a*.7})`:`rgba(75,78,74,${a*.38})`;c.beginPath();c.arc(0,-t*18,e.size*(.45+t*.7),0,Math.PI*2);c.fill()}c.restore()}}
}
