import type { VoiceFrequency } from '../data/types';
export class AudioSystem{
 ctx:AudioContext|null=null;master=.8;effects=.8;voice=.7;voiceFrequency:VoiceFrequency='Normal';lastVoice=0;
 configure(master:number,effects:number,voice:number,freq:VoiceFrequency){this.master=master;this.effects=effects;this.voice=voice;this.voiceFrequency=freq}
 ensure(){if(!this.ctx){const AC=window.AudioContext||(window as any).webkitAudioContext;this.ctx=AC?new AC():null}if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{})}
 private gain(v:number){if(!this.ctx)return null;const g=this.ctx.createGain();g.gain.value=Math.max(0,Math.min(1,v*this.master*this.effects));g.connect(this.ctx.destination);return g}
 shot(kind:'rifle'|'mg'|'cannon'|'mortar'|'missile'){this.ensure();if(!this.ctx)return;const g=this.gain((kind==='cannon'||kind==='mortar') ? .34 : .16);if(!g)return;const o=this.ctx.createOscillator(),n=this.ctx.createBufferSource(),buf=this.ctx.createBuffer(1,Math.floor(this.ctx.sampleRate*.09),this.ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);n.buffer=buf;n.connect(g);o.connect(g);o.type='square';o.frequency.value=kind==='rifle'?145:kind==='mg'?115:kind==='missile'?80:55;const t=this.ctx.currentTime;o.start(t);n.start(t);o.stop(t+.055);g.gain.exponentialRampToValueAtTime(.001,t+.12)}
 explosion(size=1){this.ensure();if(!this.ctx)return;const g=this.gain(.3*Math.min(1.4,size));if(!g)return;const src=this.ctx.createBufferSource(),len=Math.floor(this.ctx.sampleRate*.45),buf=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<len;i++){const x=1-i/len;d[i]=(Math.random()*2-1)*x*x}src.buffer=buf;const f=this.ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=420;src.connect(f);f.connect(g);const t=this.ctx.currentTime;src.start(t);g.gain.exponentialRampToValueAtTime(.001,t+.45)}
 ui(){this.ensure();if(!this.ctx)return;const g=this.gain(.08);if(!g)return;const o=this.ctx.createOscillator();o.frequency.value=520;o.connect(g);const t=this.ctx.currentTime;o.start(t);o.stop(t+.045)}
 speak(text:string,lang='en-US',urgent=false){if(this.voiceFrequency==='Off'||!('speechSynthesis'in window))return;const now=performance.now(),gap=this.voiceFrequency==='Low'?9000:this.voiceFrequency==='Normal'?5000:2700;if(!urgent&&now-this.lastVoice<gap)return;this.lastVoice=now;const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.volume=this.master*this.voice;u.rate=.95+Math.random()*.12;u.pitch=.9+Math.random()*.18;const voices=speechSynthesis.getVoices().filter(v=>v.lang.toLowerCase().startsWith(lang.split('-')[0].toLowerCase()));if(voices.length)u.voice=voices[Math.floor(Math.random()*voices.length)];speechSynthesis.speak(u)}
}
export const audio=new AudioSystem();
