import './style.css';
import { factions } from './data/factions';
import { difficultyDescriptions } from './data/difficulty';
import { towers, buildableKinds } from './data/towers';
import type { Difficulty, TargetPriority, TowerKind } from './data/types';
import { Game } from './game/Game';
import type { DefenseTeam, FacilityInstance, GameSettings } from './game/model';
import { realisticMatchup } from './systems/balance';
import { loadSaves, saveCampaign, loadSettings, saveSettings } from './systems/save';

const root=document.querySelector<HTMLDivElement>('#app')!;
let game:Game|null=null,raf=0,last=performance.now(),selectedDifficulty:Difficulty='Normal';
const LAST_FACTION='modern-defense-last-faction';
let savedFlash=0;

function factionOptions(selected:string){return factions.map(f=>`<option value="${f.id}" ${f.id===selected?'selected':''}>${f.name}</option>`).join('')}
function setupScreen(){
 const previous=game?.settings.playerFaction.id||localStorage.getItem(LAST_FACTION)||'united-states';cancelAnimationFrame(raf);game=null;
 root.innerHTML=`<main class="menu-app"><div class="menu-shell"><h1>MODERN DEFENSE</h1><p class="subtitle">Modern military outpost defense · v0.3.0 tactical overhaul</p>
 <div class="menu-actions"><button id="campaign" class="primary">Campaign</button><button id="tutorial" class="secondary">Tutorial</button><button id="settings" class="secondary">Settings</button></div>
 <section id="campaignPanel" class="card setup-grid"><label>Your faction<select id="playerFaction">${factionOptions(previous)}</select></label><label>Enemy faction<select id="enemyFaction">${factionOptions(previous==='russia'?'united-states':'russia')}</select></label><label>Branch appearance<select id="branch"></select></label><label>Campaign mission<select id="mission"></select></label></section>
 <section id="settingsPanel" class="card hidden"><label class="setting-row">UI scale <select id="uiScale"><option value=".9">Compact</option><option value="1">Default</option><option value="1.12">Large</option></select></label><label class="setting-row"><input id="autoPause" type="checkbox"> Auto-pause while upgrade menu is open</label></section>
 <div id="difficultyWrap"><h3>Difficulty</h3><div id="difficulties" class="difficulty-grid"></div><div id="matchup" class="toast"></div><section class="card progress-card"><strong>Campaign progress</strong><div id="saveInfo" class="muted"></div></section><button id="start" class="primary start-button">Start Mission</button></div>
 <p class="footer">Landscape opens fitted to the full battlefield. Pinch to zoom; drag to pan when zoomed.</p></div></main>`;
 const pf=root.querySelector<HTMLSelectElement>('#playerFaction')!,ef=root.querySelector<HTMLSelectElement>('#enemyFaction')!,branch=root.querySelector<HTMLSelectElement>('#branch')!,mission=root.querySelector<HTMLSelectElement>('#mission')!;
 function updateMission(){const s=loadSaves()[pf.value],unlocked=Math.max(1,Math.min(10,s?.mission||1));mission.innerHTML=Array.from({length:10},(_,i)=>`<option value="${i+1}" ${i+1===unlocked?'selected':''}>Mission ${i+1}${i+1>unlocked?' · locked':''}</option>`).join('');root.querySelector('#saveInfo')!.textContent=s?`Unlocked through Mission ${unlocked} · ${s.factionPoints} Faction Points · last saved ${s.updatedAt?new Date(s.updatedAt).toLocaleString():'previously'}`:'No campaign progress yet for this faction.'}
 function updateBranch(){const f=factions.find(x=>x.id===pf.value)!;branch.innerHTML=f.branchOptions.map(x=>`<option>${x}</option>`).join('')}
 function updateDiff(){const all:Difficulty[]=['Easy','Normal','Hard','Veteran','Realistic'],box=root.querySelector('#difficulties')!;box.innerHTML=all.map(d=>`<button class="difficulty ${d===selectedDifficulty?'active':''}" data-d="${d}"><strong>${d}</strong><small>${difficultyDescriptions[d]}</small></button>`).join('');box.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{selectedDifficulty=b.dataset.d as Difficulty;updateDiff();updateMatch()})}
 function updateMatch(){const p=factions.find(x=>x.id===pf.value)!,e=factions.find(x=>x.id===ef.value)!;root.querySelector('#matchup')!.innerHTML=`<strong>${p.name} vs ${e.name}</strong> · Realistic matchup: <strong>${realisticMatchup(p,e)}</strong>`}
 pf.onchange=()=>{localStorage.setItem(LAST_FACTION,pf.value);updateBranch();updateMission();updateMatch()};ef.onchange=updateMatch;updateBranch();updateMission();updateDiff();updateMatch();
 root.querySelector<HTMLButtonElement>('#campaign')!.onclick=()=>showCampaign(true);root.querySelector<HTMLButtonElement>('#settings')!.onclick=()=>{root.querySelector('#settingsPanel')!.classList.toggle('hidden')};root.querySelector<HTMLButtonElement>('#tutorial')!.onclick=()=>startTutorial();
 const settings=loadSettings({uiScale:'1',autoPause:false});const ui=root.querySelector<HTMLSelectElement>('#uiScale')!,ap=root.querySelector<HTMLInputElement>('#autoPause')!;ui.value=String(settings.uiScale);ap.checked=Boolean(settings.autoPause);ui.onchange=()=>{saveSettings({uiScale:ui.value,autoPause:ap.checked});document.documentElement.style.setProperty('--ui-scale',ui.value)};ap.onchange=()=>saveSettings({uiScale:ui.value,autoPause:ap.checked});document.documentElement.style.setProperty('--ui-scale',String(settings.uiScale));
 root.querySelector<HTMLButtonElement>('#start')!.onclick=()=>{const s=loadSaves()[pf.value],unlocked=Math.max(1,Math.min(10,s?.mission||1));if(Number(mission.value)>unlocked){alert(`Mission ${mission.value} is locked. Complete Mission ${unlocked} first.`);return;}startGame({playerFaction:factions.find(x=>x.id===pf.value)!,enemyFaction:factions.find(x=>x.id===ef.value)!,difficulty:selectedDifficulty,branch:branch.value,mission:Number(mission.value)})};
 function showCampaign(show:boolean){root.querySelector('#campaignPanel')!.classList.toggle('hidden',!show);root.querySelector('#difficultyWrap')!.classList.toggle('hidden',!show)}
}

function startTutorial(){const us=factions.find(f=>f.id==='united-states')!,op=factions.find(f=>f.id==='russia')!;startGame({playerFaction:us,enemyFaction:op,difficulty:'Easy',branch:'Army',mission:1,tutorial:true},true)}

function startGame(settings:GameSettings,tutorial=false){
 localStorage.setItem(LAST_FACTION,settings.playerFaction.id);root.innerHTML=`<main class="game-app"><div class="game-shell">
 <div class="topbar"><span class="brand">MODERN DEFENSE</span><span id="credits" class="pill"></span><span id="wave" class="pill"></span><span id="factions" class="pill faction-pill"></span><span id="saved" class="saved hidden">Saved ✓</span><button id="fit" class="secondary compact">Fit</button><button id="menu" class="secondary compact">Menu</button></div>
 <div id="stage" class="stage"><canvas id="battle" width="1800" height="1000"></canvas><div id="threat" class="threat-card"></div><div id="context" class="context-popover hidden"></div><div id="enemyCard" class="enemy-card hidden"></div><div id="tutorialHint" class="tutorial-hint ${tutorial?'':'hidden'}"></div></div>
 <div class="bottom-ui"><div id="build" class="build-strip"></div><div class="controls"><button id="nextWave" class="primary">Start Wave</button><button class="secondary speed" data-s="1">1×</button><button class="secondary speed" data-s="2">2×</button><button class="secondary speed" data-s="3">3×</button><button id="pause" class="secondary">Pause</button><button id="active" class="active-power"></button></div></div>
 </div></main>`;
 const canvas=root.querySelector<HTMLCanvasElement>('#battle')!;game=new Game(canvas,settings);game.onUpdate=updateUI;game.onGameOver=()=>{updateUI();setTimeout(()=>alert('Command Post destroyed — mission failed.'),40)};game.onVictory=()=>{if(tutorial){const prev=loadSaves()[settings.playerFaction.id]||{factionId:settings.playerFaction.id,mission:1,factionPoints:0,upgrades:{}};saveCampaign({...prev,tutorialComplete:true});flashSaved();setTimeout(()=>alert('Tutorial complete. You can replay it any time from the Main Menu.'),40);return;}const all=loadSaves(),prev=all[settings.playerFaction.id]||{factionId:settings.playerFaction.id,mission:1,factionPoints:0,upgrades:{}};const earned=2+settings.mission;saveCampaign({...prev,mission:Math.min(10,Math.max(prev.mission,settings.mission+1)),factionPoints:prev.factionPoints+earned});flashSaved();updateUI();setTimeout(()=>alert(`Mission complete! +${earned} Faction Points`),40)};
 root.querySelector('#menu')!.addEventListener('click',()=>{saveCurrentState();setupScreen()});root.querySelector('#fit')!.addEventListener('click',()=>game?.resetView());root.querySelector('#nextWave')!.addEventListener('click',()=>game?.startWave());root.querySelector('#pause')!.addEventListener('click',()=>{if(game){game.paused=!game.paused;updateUI()}});root.querySelectorAll<HTMLButtonElement>('.speed').forEach(b=>b.onclick=()=>{if(game){game.speed=Number(b.dataset.s);updateUI()}});root.querySelector('#active')!.addEventListener('click',()=>game?.useActive());
 const context=root.querySelector<HTMLDivElement>('#context')!;context.addEventListener('pointerdown',ev=>{const el=ev.target as HTMLElement,up=el.closest<HTMLButtonElement>('[data-up]'),prio=el.closest<HTMLButtonElement>('[data-priority]'),hold=el.closest<HTMLButtonElement>('[data-hold]');if(!game)return;if(up&&!up.disabled){ev.preventDefault();ev.stopPropagation();const f=currentFacility();if(f&&game.upgrade(f.id,Number(up.dataset.up))){flashSaved();renderContext()}return;}if(prio){const f=currentFacility();if(f)game.setPriority(f.id,prio.dataset.priority as TargetPriority);return;}if(hold){const f=currentFacility();if(f)game.toggleHoldFire(f.id);return;}});
 const build=root.querySelector('#build')!;build.innerHTML=buildableKinds.map(k=>`<button data-k="${k}" title="${towers[k].description}"><span>${shortLabel(k)}</span><small>${towers[k].baseCost} cr</small></button>`).join('');build.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{if(game?.build(b.dataset.k as TowerKind)){flashSaved();updateUI()}});
 if(tutorial)setupTutorial();last=performance.now();loop(last);updateUI();
}

function currentFacility():FacilityInstance|null{if(!game||!game.selected)return null;if(game.selected.type==='facility')return game.getSelected() as FacilityInstance;if(game.selected.type==='team'){const t=game.getSelected() as DefenseTeam;return game.getFacilityForTeam(t)||null}return null}
function shortLabel(k:TowerKind){const m:Record<TowerKind,string>={Command:'CP',Medical:'MED',Repair:'REP',Infantry:'INF',MachineGun:'MG',Precision:'PREC',Indirect:'MTR',AntiArmor:'AT',AirDefense:'AD',CounterUAS:'C-UAS',Recon:'RECON',Engineering:'ENG',Fortification:'FORT'};return m[k]}
function upgradeCost(kind:TowerKind,level:number){const base=Math.max(250,towers[kind].baseCost),mult=level===0?.25:level===1?.4:level===2?.65:level===3?1:1.35**(level-3);return Math.round(base*mult)}
function saveCurrentState(){if(!game||game.settings.tutorial)return;const s=loadSaves()[game.settings.playerFaction.id]||{factionId:game.settings.playerFaction.id,mission:1,factionPoints:0,upgrades:{}};saveCampaign(s);flashSaved()}
function flashSaved(){savedFlash=performance.now()+1800;const e=root.querySelector('#saved');if(e)e.classList.remove('hidden')}

function updateUI(){if(!game)return;root.querySelector('#credits')!.textContent=`${Math.floor(game.credits)} CR`;root.querySelector('#wave')!.textContent=`W${game.wave}${game.waveActive?' · ACTIVE':' · PREP'}`;root.querySelector('#factions')!.textContent=`${game.settings.playerFaction.name} vs ${game.settings.enemyFaction.name}`;
 const th=game.getThreatPreview();root.querySelector('#threat')!.innerHTML=game.waveActive?`<strong>Assault underway</strong><span>${game.enemies.length} contacts active</span>`:`<strong>Threat estimate</strong><span>${th.text}</span>`;
 const nw=root.querySelector<HTMLButtonElement>('#nextWave')!;nw.disabled=game.waveActive||game.gameOver;nw.textContent=game.victory?'Complete':game.gameOver?'Lost':game.waveActive?'Wave Active':`Start Wave ${game.wave+1}`;root.querySelector<HTMLButtonElement>('#pause')!.textContent=game.paused?'Resume':'Pause';root.querySelectorAll<HTMLButtonElement>('.speed').forEach(b=>b.classList.toggle('selected',Number(b.dataset.s)===game!.speed));
 root.querySelectorAll<HTMLButtonElement>('#build button').forEach(b=>{const k=b.dataset.k as TowerKind,built=game!.facilities.some(f=>f.def.kind===k);b.disabled=built||game!.credits<towers[k].baseCost||game!.gameOver;b.classList.toggle('built',built);b.querySelector('small')!.textContent=built?'BUILT':`${towers[k].baseCost} cr`});
 const ap=root.querySelector<HTMLButtonElement>('#active')!;ap.disabled=game.activeCooldown>0||game.gameOver;ap.innerHTML=`<strong>${game.settings.playerFaction.activePower.name}</strong><small>${game.activeCooldown>0?game.activeCooldown.toFixed(0)+'s':'READY'}</small>`;if(performance.now()>savedFlash)root.querySelector('#saved')?.classList.add('hidden');renderContext();}

function renderContext(){if(!game)return;const pop=root.querySelector<HTMLDivElement>('#context')!,enemy=root.querySelector<HTMLDivElement>('#enemyCard')!;pop.classList.add('hidden');enemy.classList.add('hidden');const obj=game.getSelected() as any;if(!obj)return;
 if(game.selected?.type==='enemy'){enemy.innerHTML=`<strong>${obj.def.label}</strong><span>${obj.faction.name}</span><span>${obj.detection} · ${obj.tacticalState}</span><span>HP ${Math.max(0,Math.round(obj.hp))}/${Math.round(obj.maxHp)}</span><span>${obj.status} · ${obj.def.armor} armor</span><span>${obj.troopCount} troops · ${obj.crewCount} crew · ${obj.def.manned?'Manned':'Unmanned'}</span>${obj.cover>0?`<span>Cover ${Math.round(obj.cover*100)}% · Suppression ${Math.round(obj.suppression*100)}%</span>`:''}`;enemy.classList.remove('hidden');return;}
 const f=currentFacility();if(!f)return;const team=game.selected?.type==='team'?game.getSelected() as DefenseTeam:null;const p=team?.pos||f.homePos,canvas=root.querySelector<HTMLCanvasElement>('#battle')!,stage=root.querySelector<HTMLDivElement>('#stage')!,cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),norm=game.worldToScreen(p),px=norm.x*cr.width+(cr.left-sr.left),py=norm.y*cr.height+(cr.top-sr.top);
 const timers=team?[team.reloadTimer>0?`Reload ${team.reloadTimer.toFixed(1)}s`:'',team.casualtyTimers.length?`Medic ${Math.min(...team.casualtyTimers).toFixed(0)}s`:'',team.repairProgress>0&&team.repairProgress<1?`Repair ${Math.round(team.repairProgress*100)}%`:''].filter(Boolean).join(' · '):f.rebuildProgress>0?`Rebuild ${Math.round(f.rebuildProgress*100)}%`:f.repairProgress>0&&f.repairProgress<1?`Repair ${Math.round(f.repairProgress*100)}%`:'';
 const priorities:TargetPriority[]=['Closest','Strongest','Infantry','Armor','Air','Drones'];pop.innerHTML=`<div class="context-head"><strong>${f.def.label}${team?' · Deployed Team':''}</strong><small>${team?team.status:f.status}${timers?' · '+timers:''}</small></div><div class="radial-upgrades">${f.upgrades.map((u,i)=>`<button data-up="${i}" ${game!.credits<upgradeCost(f.def.kind,u.level)?'disabled':''}><span>${u.name}</span><small>Lv ${u.level} · ${upgradeCost(f.def.kind,u.level)} CR</small></button>`).join('')}</div>${f.def.targets.length?`<div class="target-controls"><button data-hold="1">${f.holdFire?'Resume Fire':'Hold Fire'}</button>${priorities.map(p=>`<button data-priority="${p}" class="${f.targetPriority===p?'selected':''}">${p}</button>`).join('')}</div>`:''}`;
 pop.style.left=`${Math.max(6,Math.min(stage.clientWidth-306,px-150))}px`;pop.style.top=`${Math.max(6,Math.min(stage.clientHeight-300,py-125))}px`;pop.classList.remove('hidden');}

function setupTutorial(){const hint=root.querySelector<HTMLDivElement>('#tutorialHint')!;let step=0;const steps=['Pinch the battlefield to zoom in, then drag to pan. Tap Fit when finished.','Tap the Infantry facility or one of its deployed teams. Its engagement range appears.','Use the popup to buy any affordable upgrade.','Build Recon. Recon improves detection and identification instead of attacking.','Build Fortifications. The perimeter becomes stronger and engineers can later repair breaches.','Start Wave 1. Watch enemies spread, use cover, suppress, maneuver, breach, and assault.','Observe automatic medics and repair teams if defenders are hurt or damaged.','Use your faction active power, then survive the tutorial mission.'];function show(){hint.innerHTML=`<strong>Tutorial ${step+1}/${steps.length}</strong><span>${steps[step]}</span><button id="tutorialNext" class="secondary">${step===steps.length-1?'Hide':'Next'}</button>`;hint.querySelector<HTMLButtonElement>('#tutorialNext')!.onclick=()=>{if(step<steps.length-1){step++;show()}else hint.classList.add('hidden')}}show()}
function loop(now:number){if(!game)return;const dt=Math.min(.033,(now-last)/1000);last=now;game.update(dt);game.draw();raf=requestAnimationFrame(loop)}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game){game.paused=true;updateUI()}});setupScreen();
