import './style.css';
import { factions } from './data/factions';
import { difficultyDescriptions } from './data/difficulty';
import { campaignFor } from './data/missions';
import { buildings,buildableBuildings } from './data/buildings';
import { equipment,equipmentById,defaultLoadout } from './data/equipment';
import { units } from './data/units';
import type { BuildingKind,Difficulty,GameSettings,GraphicsQuality,LoadoutPreset,UnitOrder,VoiceFrequency } from './data/types';
import type { BuildingInstance,UnitInstance } from './game/model';
import { Game } from './game/Game';
import { getFactionProgress,loadSettings,saveFactionProgress,saveSettings,type UserSettings } from './systems/save';

const root=document.querySelector<HTMLDivElement>('#app')!;let game:Game|null=null;let raf=0,last=performance.now();let selectedDifficulty:Difficulty='Normal';let menuFaction='united-states';let menuEnemy='russia';let menuMission=1;let selectedLoadout=0;
const difficulties:Difficulty[]=['Easy','Normal','Hard','Veteran','Realistic'];
function factionById(id:string){return factions.find(f=>f.id===id)||factions[0]}
function opts(selected:string){return factions.map(f=>`<option value="${f.id}" ${f.id===selected?'selected':''}>${f.name}</option>`).join('')}
function esc(s:string){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!))}

function showMenu(tab:'campaign'|'armory'|'loadout'|'settings'='campaign'){
 cancelAnimationFrame(raf);game=null;const p=getFactionProgress(menuFaction),settings=loadSettings(),camp=campaignFor(factionById(menuFaction),factionById(menuEnemy));const unlocked=Math.max(1,Math.min(10,p.campaigns[menuEnemy]||1));menuMission=Math.min(menuMission,unlocked);selectedLoadout=Math.min(selectedLoadout,p.loadouts.length-1);
 root.innerHTML=`<main class="menu-app"><div class="menu-shell wide"><header class="brand"><div><h1>MODERN DEFENSE</h1><p>Combined-arms tactical campaign · v0.4.0 major rebuild</p></div><div class="fp-pill"><span>Faction Points</span><strong>${p.factionPoints}</strong></div></header>
 <nav class="tabs"><button data-tab="campaign" class="${tab==='campaign'?'active':''}">Campaign</button><button data-tab="armory" class="${tab==='armory'?'active':''}">Faction Unlocks</button><button data-tab="loadout" class="${tab==='loadout'?'active':''}">Loadout</button><button data-tab="settings" class="${tab==='settings'?'active':''}">Settings</button><button id="tutorialBtn">Tutorial</button></nav>
 <section id="menuContent"></section><footer>Landscape recommended · pinch to zoom · one-finger pan while zoomed · tap units to command them</footer></div></main>`;
 root.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>showMenu(b.dataset.tab as any));root.querySelector<HTMLButtonElement>('#tutorialBtn')!.onclick=()=>startTutorial();
 if(tab==='campaign')renderCampaign(p,unlocked);if(tab==='armory')renderArmory(p);if(tab==='loadout')renderLoadout(p);if(tab==='settings')renderSettings(settings);
}

function renderCampaign(p:any,unlocked:number){const camp=campaignFor(factionById(menuFaction),factionById(menuEnemy));const content=root.querySelector('#menuContent')!;content.innerHTML=`<section class="campaign-grid"><div class="card setup-card"><h2>Matchup Campaign</h2><label>Player faction<select id="playerFaction">${opts(menuFaction)}</select></label><label>Opponent<select id="enemyFaction">${opts(menuEnemy)}</select></label><div class="campaign-title"><strong>${camp.title}</strong><span>${camp.synopsis}</span></div><label>Mission<select id="missionSel">${camp.missions.map(m=>`<option value="${m.number}" ${m.number===menuMission?'selected':''} ${m.number>unlocked?'disabled':''}>${m.number}. ${m.title}${m.number>unlocked?' · LOCKED':''}</option>`).join('')}</select></label><label>Difficulty<select id="diffSel">${difficulties.map(d=>`<option ${d===selectedDifficulty?'selected':''}>${d}</option>`).join('')}</select></label><div id="diffDesc" class="hint"></div></div>
 <div class="card briefing-card" id="briefing"></div></section><button id="startMission" class="primary huge">Start Operation</button>`;
 const pf=content.querySelector<HTMLSelectElement>('#playerFaction')!,ef=content.querySelector<HTMLSelectElement>('#enemyFaction')!,ms=content.querySelector<HTMLSelectElement>('#missionSel')!,ds=content.querySelector<HTMLSelectElement>('#diffSel')!;
 pf.onchange=()=>{menuFaction=pf.value;selectedLoadout=0;showMenu('campaign')};ef.onchange=()=>{menuEnemy=ef.value;menuMission=1;showMenu('campaign')};ms.onchange=()=>{menuMission=Number(ms.value);renderBriefing()};ds.onchange=()=>{selectedDifficulty=ds.value as Difficulty;content.querySelector('#diffDesc')!.textContent=difficultyDescriptions[selectedDifficulty]};content.querySelector('#diffDesc')!.textContent=difficultyDescriptions[selectedDifficulty];
 function renderBriefing(){const m=campaignFor(factionById(menuFaction),factionById(menuEnemy)).missions[menuMission-1];content.querySelector('#briefing')!.innerHTML=`<div class="op-kicker">${m.operation}</div><h2>${m.title}</h2><div class="mission-meta"><span>${m.mapTheme}</span><span>${m.weather}</span><span>${m.timeOfDay}</span><span>${m.type.replace(/([A-Z])/g,' $1').trim()}</span></div><p>${m.briefing}</p><h3>Primary</h3><p>${m.primary}</p><h3>Secondary</h3><ul>${m.secondary.map(x=>`<li>${x}</li>`).join('')}</ul><div class="intel-box"><strong>Known progression</strong><span>Enemy capability escalates with mission number and doctrine rather than simple HP inflation.</span></div><div class="mission-stats"><span>Starting credits <b>${m.startingCredits}</b></span><span>Deployment capacity <b>${m.deploymentCapacity}</b></span><span>Assault phases <b>${m.waves}</b></span></div>`}
 renderBriefing();content.querySelector<HTMLButtonElement>('#startMission')!.onclick=()=>startMission(false);
}

function renderArmory(p:any){const content=root.querySelector('#menuContent')!;const categories=['Personnel','Primary','SupportWeapon','Optic','Armor','Specialist','Vehicle','Aviation','Support'];content.innerHTML=`<section class="card"><div class="section-head"><div><h2>${factionById(menuFaction).name} Faction Unlocks</h2><p>Every unlock changes an actual gameplay capability and becomes selectable in Loadout.</p></div><strong>${p.factionPoints} FP available</strong></div>${categories.map(cat=>`<div class="armory-section"><h3>${cat.replace('SupportWeapon','Support Weapons')}</h3><div class="unlock-grid">${equipment.filter(e=>e.category===cat).map(e=>unlockCard(e,p)).join('')}</div></div>`).join('')}</section>`;
 content.querySelectorAll<HTMLButtonElement>('[data-unlock]').forEach(b=>b.onclick=()=>{const id=b.dataset.unlock!,item=equipmentById[id];const prog=getFactionProgress(menuFaction);if(prog.unlocked.includes(id))return;const missing=item.requires.find(r=>!prog.unlocked.includes(r));if(missing)return alert(`Requires ${equipmentById[missing]?.name||missing}`);if(prog.factionPoints<item.fpCost)return alert('Not enough Faction Points.');prog.factionPoints-=item.fpCost;prog.unlocked.push(id);saveFactionProgress(prog);showMenu('armory')});
}
function unlockCard(e:any,p:any){const owned=p.unlocked.includes(e.id),missing=e.requires.find((r:string)=>!p.unlocked.includes(r));return `<article class="unlock-card ${owned?'owned':''}"><div><strong>${e.name}</strong><small>Tier ${e.tier}</small></div><p>${e.description}</p><div class="effect">${e.effect}</div><button data-unlock="${e.id}" ${owned||missing||p.factionPoints<e.fpCost?'disabled':''}>${owned?'Unlocked':missing?`Requires ${equipmentById[missing]?.name}`:`Unlock · ${e.fpCost} FP`}</button></article>`}

function renderLoadout(p:any){const content=root.querySelector('#menuContent')!;const l={...defaultLoadout,...p.loadouts[selectedLoadout]};const available=(cat:string)=>equipment.filter(e=>e.category===cat&&p.unlocked.includes(e.id));const select=(id:string,cat:string,current:string)=>`<select id="${id}">${available(cat).map(e=>`<option value="${e.id}" ${e.id===current?'selected':''}>${e.name}</option>`).join('')}</select>`;content.innerHTML=`<section class="loadout-layout"><div class="card"><div class="section-head"><div><h2>Force Loadout</h2><p>Faction Points unlock options; this screen decides what your force actually fields.</p></div><button id="newPreset" class="secondary">Duplicate Preset</button></div><label>Preset<select id="preset">${p.loadouts.map((x:any,i:number)=>`<option value="${i}" ${i===selectedLoadout?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Preset name<input id="presetName" value="${esc(l.name)}"></label><div class="loadout-grid"><label>Personnel${select('personnel','Personnel',l.personnel)}</label><label>Primary weapon${select('primary','Primary',l.primary)}</label><label>Support weapon${select('supportWeapon','SupportWeapon',l.supportWeapon)}</label><label>Optic${select('optic','Optic',l.optic)}</label><label>Protection${select('armor','Armor',l.armor)}</label><label>Vehicle${select('vehicle','Vehicle',l.vehicle)}</label><label>Aviation${select('aviation','Aviation',l.aviation)}</label></div><h3>Specialists</h3><div class="check-grid">${available('Specialist').map(e=>`<label><input type="checkbox" data-specialist="${e.id}" ${l.specialists.includes(e.id)?'checked':''}> ${e.name}</label>`).join('')||'<span class="muted">Unlock specialists with Faction Points.</span>'}</div><h3>Command support</h3><div class="check-grid">${available('Support').map(e=>`<label><input type="checkbox" data-support="${e.id}" ${l.support.includes(e.id)?'checked':''}> ${e.name}</label>`).join('')||'<span class="muted">No support assets unlocked.</span>'}</div><button id="saveLoadout" class="primary">Save Loadout</button></div><div class="card"><h2>What this loadout changes</h2><div id="loadoutEffects" class="effect-list"></div></div></section>`;
 content.querySelector<HTMLSelectElement>('#preset')!.onchange=e=>{selectedLoadout=Number((e.target as HTMLSelectElement).value);showMenu('loadout')};content.querySelector<HTMLButtonElement>('#newPreset')!.onclick=()=>{const prog=getFactionProgress(menuFaction);prog.loadouts.push({...l,name:`Preset ${prog.loadouts.length+1}`,specialists:[...l.specialists],support:[...l.support]});saveFactionProgress(prog);selectedLoadout=prog.loadouts.length-1;showMenu('loadout')};
 const ids=['personnel','primary','supportWeapon','optic','armor','vehicle','aviation'];function effects(){const chosen=ids.map(id=>equipmentById[(content.querySelector(`#${id}`) as HTMLSelectElement)?.value]).filter(Boolean);chosen.push(...[...content.querySelectorAll<HTMLInputElement>('[data-specialist]:checked')].map(x=>equipmentById[x.dataset.specialist!]));chosen.push(...[...content.querySelectorAll<HTMLInputElement>('[data-support]:checked')].map(x=>equipmentById[x.dataset.support!]));content.querySelector('#loadoutEffects')!.innerHTML=chosen.map(e=>`<div><strong>${e.name}</strong><span>${e.effect}</span></div>`).join('')}
 content.querySelectorAll('select,input[type="checkbox"]').forEach(el=>el.addEventListener('change',effects));effects();content.querySelector<HTMLButtonElement>('#saveLoadout')!.onclick=()=>{const prog=getFactionProgress(menuFaction);const out:LoadoutPreset={name:(content.querySelector<HTMLInputElement>('#presetName')!.value||'Loadout').slice(0,24),personnel:(content.querySelector<HTMLSelectElement>('#personnel')!.value),primary:content.querySelector<HTMLSelectElement>('#primary')!.value,supportWeapon:content.querySelector<HTMLSelectElement>('#supportWeapon')!.value,optic:content.querySelector<HTMLSelectElement>('#optic')!.value,armor:content.querySelector<HTMLSelectElement>('#armor')!.value,vehicle:content.querySelector<HTMLSelectElement>('#vehicle')!.value,aviation:content.querySelector<HTMLSelectElement>('#aviation')!.value,specialists:[...content.querySelectorAll<HTMLInputElement>('[data-specialist]:checked')].map(x=>x.dataset.specialist!),support:[...content.querySelectorAll<HTMLInputElement>('[data-support]:checked')].map(x=>x.dataset.support!)};prog.loadouts[selectedLoadout]=out;saveFactionProgress(prog);showMenu('loadout')};
}

function renderSettings(s:UserSettings){const content=root.querySelector('#menuContent')!;content.innerHTML=`<section class="card settings-card"><h2>Settings</h2><div class="settings-grid"><label>Graphics<select id="graphics"><option>Battery</option><option>Balanced</option><option>High</option></select></label><label>Voice chatter<select id="voiceFrequency"><option>Off</option><option>Low</option><option>Normal</option><option>High</option></select></label><label>Master volume<input id="masterVolume" type="range" min="0" max="1" step=".05" value="${s.masterVolume}"></label><label>Combat effects<input id="effectsVolume" type="range" min="0" max="1" step=".05" value="${s.effectsVolume}"></label><label>Voices<input id="voiceVolume" type="range" min="0" max="1" step=".05" value="${s.voiceVolume}"></label><label>UI scale<input id="uiScale" type="range" min=".85" max="1.25" step=".05" value="${s.uiScale}"></label><label class="check"><input id="autoPause" type="checkbox" ${s.autoPause?'checked':''}> Auto-pause when inspecting upgrades</label></div><button id="saveSettings" class="primary">Save Settings</button></section>`;content.querySelector<HTMLSelectElement>('#graphics')!.value=s.graphics;content.querySelector<HTMLSelectElement>('#voiceFrequency')!.value=s.voiceFrequency;content.querySelector<HTMLButtonElement>('#saveSettings')!.onclick=()=>{const out:UserSettings={graphics:content.querySelector<HTMLSelectElement>('#graphics')!.value as GraphicsQuality,voiceFrequency:content.querySelector<HTMLSelectElement>('#voiceFrequency')!.value as VoiceFrequency,masterVolume:Number(content.querySelector<HTMLInputElement>('#masterVolume')!.value),effectsVolume:Number(content.querySelector<HTMLInputElement>('#effectsVolume')!.value),voiceVolume:Number(content.querySelector<HTMLInputElement>('#voiceVolume')!.value),uiScale:Number(content.querySelector<HTMLInputElement>('#uiScale')!.value),autoPause:content.querySelector<HTMLInputElement>('#autoPause')!.checked};saveSettings(out);document.documentElement.style.setProperty('--ui-scale',String(out.uiScale));showMenu('settings')};}

function startTutorial(){menuFaction='united-states';menuEnemy='russia';menuMission=1;startMission(true)}
function startMission(tutorial:boolean){const player=factionById(menuFaction),enemy=factionById(menuEnemy),progress=getFactionProgress(menuFaction),loadout=progress.loadouts[selectedLoadout]||defaultLoadout,mission=campaignFor(player,enemy).missions[(tutorial?1:menuMission)-1],s=loadSettings();const settings:GameSettings={playerFaction:player,enemyFaction:enemy,difficulty:tutorial?'Easy':selectedDifficulty,branch:player.branchOptions[0],mission,loadout,tutorial,graphics:s.graphics,voiceFrequency:s.voiceFrequency,masterVolume:s.masterVolume,effectsVolume:s.effectsVolume,voiceVolume:s.voiceVolume,uiScale:s.uiScale,autoPause:s.autoPause};renderGame(settings)}

function renderGame(settings:GameSettings){root.innerHTML=`<main class="game-app"><div class="game-shell"><header class="hud"><div><strong>${settings.mission.operation}</strong><span>${settings.mission.title}</span></div><div class="hud-center"><span id="credits"></span><span id="phase"></span><span id="objective"></span></div><div class="hud-actions"><button id="fit">Fit</button><button id="pause">Pause</button><button id="menu">Menu</button></div></header><section class="battle-wrap"><canvas id="battle" width="1536" height="864"></canvas><div id="threat" class="threat-card"></div><div id="events" class="event-feed"></div><div id="context" class="context-panel hidden"></div><div id="tutorialHint" class="tutorial-hint ${settings.tutorial?'':'hidden'}"></div></section><footer class="command-bar"><div id="buildingsBar" class="bar-group"></div><div id="unitsBar" class="bar-group"></div><div id="ordersBar" class="bar-group"></div><div class="bar-group compact"><button id="startPhase" class="primary">Start Phase</button><button id="active" class="active-power"></button></div></footer></div></main>`;
 const canvas=root.querySelector<HTMLCanvasElement>('#battle')!;game=new Game(canvas,settings);game.onUpdate=updateGameUI;game.onEvent=()=>updateGameUI();game.onVictory=()=>{const p=getFactionProgress(settings.playerFaction.id);const key=settings.enemyFaction.id;const current=p.campaigns[key]||1;p.campaigns[key]=Math.min(10,Math.max(current,settings.mission.number+1));const earned=2+Math.ceil(settings.mission.number/2);p.factionPoints+=earned;saveFactionProgress(p);setTimeout(()=>alert(`Mission complete! +${earned} Faction Points`),50)};game.onGameOver=()=>setTimeout(()=>alert('Mission failed.'),50);
 root.querySelector<HTMLButtonElement>('#fit')!.onclick=()=>game?.resetView();root.querySelector<HTMLButtonElement>('#pause')!.onclick=()=>{if(game){game.paused=!game.paused;updateGameUI()}};root.querySelector<HTMLButtonElement>('#menu')!.onclick=()=>showMenu('campaign');root.querySelector<HTMLButtonElement>('#startPhase')!.onclick=()=>game?.startPhase();root.querySelector<HTMLButtonElement>('#active')!.onclick=()=>game?.useActive();
 const orders:UnitOrder[]=['Move','Defend','Overwatch','SupportByFire','Assault','Breach','Fallback','Hold'];root.querySelector('#ordersBar')!.innerHTML=orders.map(o=>`<button data-order="${o}">${o.replace('SupportByFire','Support Fire')}</button>`).join('');root.querySelectorAll<HTMLButtonElement>('[data-order]').forEach(b=>b.onclick=()=>{if(!game)return;const o=b.dataset.order as UnitOrder;if(['Move','Assault','Breach','Fallback'].includes(o))game.setOrderMode(o);else game.issueOrder(o)});
 if(settings.tutorial)setupTutorial();last=performance.now();loop(last);updateGameUI();}

function updateGameUI(){if(!game)return;root.querySelector('#credits')!.textContent=`${Math.floor(game.credits)} CR`;root.querySelector('#phase')!.textContent=`Phase ${game.phase}/${game.settings.mission.waves}`;root.querySelector('#objective')!.textContent=game.settings.mission.primary;root.querySelector<HTMLButtonElement>('#pause')!.textContent=game.paused?'Resume':'Pause';const th=root.querySelector('#threat')!;th.innerHTML=game.phaseActive?`<strong>Enemy action underway</strong><span>${game.units.filter(u=>u.side==='Enemy'&&!u.destroyed).length} contacts on field</span>`:`<strong>Next threat estimate</strong><span>${game.threatPreview()}</span>`;root.querySelector('#events')!.innerHTML=game.events.map(e=>`<div class="event ${e.priority.toLowerCase()}">${e.text}</div>`).join('');renderBuildBars();renderContext();const sp=root.querySelector<HTMLButtonElement>('#startPhase')!;sp.disabled=game.phaseActive||game.gameOver;sp.textContent=game.gameOver?(game.victory?'Complete':'Failed'):game.phaseActive?'Phase Active':`Begin Phase ${game.phase+1}`;const ap=root.querySelector<HTMLButtonElement>('#active')!;ap.disabled=game.activeCooldown>0||game.gameOver;ap.innerHTML=`<strong>${game.settings.playerFaction.activePower.name}</strong><small>${game.activeCooldown>0?`${game.activeCooldown.toFixed(0)}s`:'READY'}</small>`;}
function renderBuildBars(){if(!game)return;const bb=root.querySelector('#buildingsBar')!,ub=root.querySelector('#unitsBar')!;if(game.settings.mission.type==='BaseDefense'){bb.innerHTML=buildableBuildings.map(k=>{const built=game!.buildings.some(b=>b.kind===k),d=buildings[k];return `<button data-build="${k}" ${built||game!.credits<d.baseCost?'disabled':''}><b>${built?'✓ ':''}${d.name.replace(' Facility','')}</b><small>${built?'BUILT':`${d.baseCost} CR`}</small></button>`}).join('');bb.querySelectorAll<HTMLButtonElement>('[data-build]').forEach(b=>b.onclick=()=>{game?.build(b.dataset.build as BuildingKind);updateGameUI()});const available=game.availableUnitIds();ub.innerHTML=available.map(id=>{const d=units[id],count=game!.units.filter(u=>u.side==='Friendly'&&u.def.id===id&&!u.destroyed).length,cap=game!.capacityFor(id);return `<button data-unit="${id}" ${game!.credits<d.cost||count>=cap?'disabled':''}><b>${d.name}</b><small>${d.cost} CR · ${count}/${cap}</small></button>`}).join('');ub.querySelectorAll<HTMLButtonElement>('[data-unit]').forEach(b=>b.onclick=()=>{game?.deployUnit(b.dataset.unit!);updateGameUI()})}else{bb.innerHTML='<span class="bar-note">No base construction in this mission</span>';ub.innerHTML='<span class="bar-note">Command your deployed force</span>'}}
function renderContext(){if(!game)return;const box=root.querySelector<HTMLDivElement>('#context')!,obj=game.getSelected() as any;box.classList.add('hidden');if(!obj)return;if(game.selection?.type==='unit'){const u=obj as UnitInstance;const wounded=u.soldiers.filter(s=>s.state==='Wounded').length,medics=u.soldiers.filter(s=>s.medic).length,alive=u.soldiers.filter(s=>s.state!=='Wounded').length;box.innerHTML=`<div class="context-head"><div><strong>${u.def.name}</strong><small>${u.side} · ${u.order} · ${u.status}</small></div><span class="domain-badge">${u.def.domain}</span></div><div class="status-grid"><span>HP <b>${Math.max(0,Math.round(u.hp))}/${Math.round(u.maxHp)}</b></span><span>Range <b>${Math.round(game.effectiveRange(u))}</b></span><span>Weapons <b>${u.weapons}</b></span><span>Ammo <b>${u.ammo}/${u.def.magazine}</b></span>${u.def.domain==='Infantry'?`<span>Ready troops <b>${alive}/${u.soldiers.length}</b></span><span>Wounded <b>${wounded}</b></span><span>Medics <b>${medics}</b></span>`:''}<span>Suppression <b>${Math.round(u.suppression*100)}%</b></span></div><p>${u.def.description}</p>`;box.classList.remove('hidden');return}
 const b=obj as BuildingInstance;const views=game.getUpgradeViews(b);box.innerHTML=`<div class="context-head"><div><strong>${buildings[b.kind].name}</strong><small>${buildings[b.kind].description}</small></div></div><div class="upgrade-list">${views.map(v=>`<button data-upgrade="${v.def.id}" ${v.lockedReason||game!.credits<v.cost?'disabled':''}><span><strong>${v.def.name}</strong><small>${v.def.description}</small></span><span><b>${v.lockedReason||`${v.cost} CR`}</b><small>${v.def.effect}</small></span></button>`).join('')||'<span class="muted">No direct upgrades.</span>'}</div>`;box.classList.remove('hidden');box.querySelectorAll<HTMLButtonElement>('[data-upgrade]').forEach(btn=>btn.onclick=()=>{if(game?.buyUpgrade(b.id,btn.dataset.upgrade!))updateGameUI()})}
function setupTutorial(){const h=root.querySelector<HTMLDivElement>('#tutorialHint')!;const steps=['Pinch to zoom, drag to pan, and use Fit to restore the full battlefield.','The Command Post is your only starting building. Tap it to inspect Recon, Command and Fortification upgrades.','Build an Infantry Facility, then deploy a Rifle Squad.','Tap the squad. Choose Move, then tap a destination on the map.','Buy Recon at the CP. Recon improves detection and effective engagement range without exceeding a weapon’s physical capability.','Upgrade infantry organization. Additional Squad adds another complete copy of the current squad loadout.','Start the first enemy phase and watch individual soldiers, suppression, cover use, tracers, explosions and doctrine-driven movement.','Medics are personnel, not a building. A medic can treat casualties in another reachable squad.'];let i=0;function draw(){h.innerHTML=`<strong>Tutorial ${i+1}/${steps.length}</strong><span>${steps[i]}</span><button>${i===steps.length-1?'Hide':'Next'}</button>`;h.querySelector('button')!.onclick=()=>{if(i<steps.length-1){i++;draw()}else h.classList.add('hidden')}}draw()}
function loop(now:number){if(!game)return;const dt=Math.min(.033,(now-last)/1000);last=now;game.update(dt);game.draw();raf=requestAnimationFrame(loop)}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game){game.paused=true;updateGameUI()}});const s=loadSettings();document.documentElement.style.setProperty('--ui-scale',String(s.uiScale));showMenu();
